id: fan
display_name: Fan
brightness_limit: 0.1
weather_sets_module: projects.fan.weather_params
event_map_module: projects.fan.event_map
groups:
- id: main
  width: 128
  height: 300
geometry:
  type: fan
hooks:
  random_events: projects.fan.random_events
startup_weather_set: ocean
startup_weather_state: ocean_kelp_forest
receivers:
- ip: 192.168.68.140
  protocol: sacn
  object_id: 0
  strips:
  - group: main
    strip_idx: 0
    kind: column
    length: 300
    direction: down
    col: 0
  - group: main
    strip_idx: 1
    kind: column
    length: 300
    direction: up
    col: 1
  - group: main
    strip_idx: 2
    kind: column
    length: 300
    direction: down
    col: 2
  - group: main
    strip_idx: 3
    kind: column
    length: 300
    direction: up
    col: 3
  - group: main
    strip_idx: 4
    kind: column
    length: 300
    direction: down
    col: 4
  - group: main
    strip_idx: 5
    kind: column
    length: 300
    direction: up
    col: 5
  - group: main
    strip_idx: 6
    kind: column
    length: 300
    direction: down
    col: 6
  - group: main
    strip_idx: 7
    kind: column
    length: 300
    direction: up
    col: 7
  - group: main
    strip_idx: 8
    kind: column
    length: 300
    direction: down
    col: 8
  - group: main
    strip_idx: 9
    kind: column
    length: 300
    direction: up
    col: 9
  - group: main
    strip_idx: 10
    kind: column
    length: 300
    direction: down
    col: 10
  - group: main
    strip_idx: 11
    kind: column
    length: 300
    direction: up
    col: 11
  - group: main
    strip_idx: 12
    kind: column
    length: 300
    direction: down
    col: 12
  - group: main
    strip_idx: 13
    kind: column
    length: 300
    direction: up
    col: 13
  - group: main
    strip_idx: 14
    kind: column
    length: 300
    direction: down
    col: 14
  - group: main
    strip_idx: 15
    kind: column
    length: 300
    direction: up
    col: 15
  - group: main
    strip_idx: 16
    kind: column
    length: 300
    direction: down
    col: 16
  - group: main
    strip_idx: 17
    kind: column
    length: 300
    direction: up
    col: 17
  - group: main
    strip_idx: 18
    kind: column
    length: 300
    direction: down
    col: 18
  - group: main
    strip_idx: 19
    kind: column
    length: 300
    direction: up
    col: 19
  - group: main
    strip_idx: 20
    kind: column
    length: 300
    direction: down
    col: 20
  - group: main
    strip_idx: 21
    kind: column
    length: 300
    direction: up
    col: 21
  - group: main
    strip_idx: 22
    kind: column
    length: 300
    direction: down
    col: 22
  - group: main
    strip_idx: 23
    kind: column
    length: 300
    direction: up
    col: 23
  - group: main
    strip_idx: 24
    kind: column
    length: 300
    direction: down
    col: 24
  - group: main
    strip_idx: 25
    kind: column
    length: 300
    direction: up
    col: 25
  - group: main
    strip_idx: 26
    kind: column
    length: 300
    direction: down
    col: 26
  - group: main
    strip_idx: 27
    kind: column
    length: 300
    direction: up
    col: 27
  - group: main
    strip_idx: 28
    kind: column
    length: 300
    direction: down
    col: 28
  - group: main
    strip_idx: 29
    kind: column
    length: 300
    direction: up
    col: 29
  - group: main
    strip_idx: 30
    kind: column
    length: 300
    direction: down
    col: 30
  - group: main
    strip_idx: 31
    kind: column
    length: 300
    direction: up
    col: 31
- ip: 192.168.68.141
  protocol: sacn
  object_id: 1
  strips:
  - group: main
    strip_idx: 0
    kind: column
    length: 300
    direction: down
    col: 32
  - group: main
    strip_idx: 1
    kind: column
    length: 300
    direction: up
    col: 33
  - group: main
    strip_idx: 2
    kind: column
    length: 300
    direction: down
    col: 34
  - group: main
    strip_idx: 3
    kind: column
    length: 300
    direction: up
    col: 35
  - group: main
    strip_idx: 4
    kind: column
    length: 300
    direction: down
    col: 36
  - group: main
    strip_idx: 5
    kind: column
    length: 300
    direction: up
    col: 37
  - group: main
    strip_idx: 6
    kind: column
    length: 300
    direction: down
    col: 38
  - group: main
    strip_idx: 7
    kind: column
    length: 300
    direction: up
    col: 39
  - group: main
    strip_idx: 8
    kind: column
    length: 300
    direction: down
    col: 40
  - group: main
    strip_idx: 9
    kind: column
    length: 300
    direction: up
    col: 41
  - group: main
    strip_idx: 10
    kind: column
    length: 300
    direction: down
    col: 42
  - group: main
    strip_idx: 11
    kind: column
    length: 300
    direction: up
    col: 43
  - group: main
    strip_idx: 12
    kind: column
    length: 300
    direction: down
    col: 44
  - group: main
    strip_idx: 13
    kind: column
    length: 300
    direction: up
    col: 45
  - group: main
    strip_idx: 14
    kind: column
    length: 300
    direction: down
    col: 46
  - group: main
    strip_idx: 15
    kind: column
    length: 300
    direction: up
    col: 47
  - group: main
    strip_idx: 16
    kind: column
    length: 300
    direction: down
    col: 48
  - group: main
    strip_idx: 17
    kind: column
    length: 300
    direction: up
    col: 49
  - group: main
    strip_idx: 18
    kind: column
    length: 300
    direction: down
    col: 50
  - group: main
    strip_idx: 19
    kind: column
    length: 300
    direction: up
    col: 51
  - group: main
    strip_idx: 20
    kind: column
    length: 300
    direction: down
    col: 52
  - group: main
    strip_idx: 21
    kind: column
    length: 300
    direction: up
    col: 53
  - group: main
    strip_idx: 22
    kind: column
    length: 300
    direction: down
    col: 54
  - group: main
    strip_idx: 23
    kind: column
    length: 300
    direction: up
    col: 55
  - group: main
    strip_idx: 24
    kind: column
    length: 300
    direction: down
    col: 56
  - group: main
    strip_idx: 25
    kind: column
    length: 300
    direction: up
    col: 57
  - group: main
    strip_idx: 26
    kind: column
    length: 300
    direction: down
    col: 58
  - group: main
    strip_idx: 27
    kind: column
    length: 300
    direction: up
    col: 59
  - group: main
    strip_idx: 28
    kind: column
    length: 300
    direction: down
    col: 60
  - group: main
    strip_idx: 29
    kind: column
    length: 300
    direction: up
    col: 61
  - group: main
    strip_idx: 30
    kind: column
    length: 300
    direction: down
    col: 62
  - group: main
    strip_idx: 31
    kind: column
    length: 300
    direction: up
    col: 63
- ip: 192.168.68.142
  protocol: sacn
  object_id: 2
  strips:
  - group: main
    strip_idx: 0
    kind: column
    length: 300
    direction: down
    col: 64
  - group: main
    strip_idx: 1
    kind: column
    length: 300
    direction: up
    col: 65
  - group: main
    strip_idx: 2
    kind: column
    length: 300
    direction: down
    col: 66
  - group: main
    strip_idx: 3
    kind: column
    length: 300
    direction: up
    col: 67
  - group: main
    strip_idx: 4
    kind: column
    length: 300
    direction: down
    col: 68
  - group: main
    strip_idx: 5
    kind: column
    length: 300
    direction: up
    col: 69
  - group: main
    strip_idx: 6
    kind: column
    length: 300
    direction: down
    col: 70
  - group: main
    strip_idx: 7
    kind: column
    length: 300
    direction: up
    col: 71
  - group: main
    strip_idx: 8
    kind: column
    length: 300
    direction: down
    col: 72
  - group: main
    strip_idx: 9
    kind: column
    length: 300
    direction: up
    col: 73
  - group: main
    strip_idx: 10
    kind: column
    length: 300
    direction: down
    col: 74
  - group: main
    strip_idx: 11
    kind: column
    length: 300
    direction: up
    col: 75
  - group: main
    strip_idx: 12
    kind: column
    length: 300
    direction: down
    col: 76
  - group: main
    strip_idx: 13
    kind: column
    length: 300
    direction: up
    col: 77
  - group: main
    strip_idx: 14
    kind: column
    length: 300
    direction: down
    col: 78
  - group: main
    strip_idx: 15
    kind: column
    length: 300
    direction: up
    col: 79
  - group: main
    strip_idx: 16
    kind: column
    length: 300
    direction: down
    col: 80
  - group: main
    strip_idx: 17
    kind: column
    length: 300
    direction: up
    col: 81
  - group: main
    strip_idx: 18
    kind: column
    length: 300
    direction: down
    col: 82
  - group: main
    strip_idx: 19
    kind: column
    length: 300
    direction: up
    col: 83
  - group: main
    strip_idx: 20
    kind: column
    length: 300
    direction: down
    col: 84
  - group: main
    strip_idx: 21
    kind: column
    length: 300
    direction: up
    col: 85
  - group: main
    strip_idx: 22
    kind: column
    length: 300
    direction: down
    col: 86
  - group: main
    strip_idx: 23
    kind: column
    length: 300
    direction: up
    col: 87
  - group: main
    strip_idx: 24
    kind: column
    length: 300
    direction: down
    col: 88
  - group: main
    strip_idx: 25
    kind: column
    length: 300
    direction: up
    col: 89
  - group: main
    strip_idx: 26
    kind: column
    length: 300
    direction: down
    col: 90
  - group: main
    strip_idx: 27
    kind: column
    length: 300
    direction: up
    col: 91
  - group: main
    strip_idx: 28
    kind: column
    length: 300
    direction: down
    col: 92
  - group: main
    strip_idx: 29
    kind: column
    length: 300
    direction: up
    col: 93
  - group: main
    strip_idx: 30
    kind: column
    length: 300
    direction: down
    col: 94
  - group: main
    strip_idx: 31
    kind: column
    length: 300
    direction: up
    col: 95
- ip: 192.168.68.143
  protocol: sacn
  object_id: 3
  strips:
  - group: main
    strip_idx: 0
    kind: column
    length: 300
    direction: down
    col: 96
  - group: main
    strip_idx: 1
    kind: column
    length: 300
    direction: up
    col: 97
  - group: main
    strip_idx: 2
    kind: column
    length: 300
    direction: down
    col: 98
  - group: main
    strip_idx: 3
    kind: column
    length: 300
    direction: up
    col: 99
  - group: main
    strip_idx: 4
    kind: column
    length: 300
    direction: down
    col: 100
  - group: main
    strip_idx: 5
    kind: column
    length: 300
    direction: up
    col: 101
  - group: main
    strip_idx: 6
    kind: column
    length: 300
    direction: down
    col: 102
  - group: main
    strip_idx: 7
    kind: column
    length: 300
    direction: up
    col: 103
  - group: main
    strip_idx: 8
    kind: column
    length: 300
    direction: down
    col: 104
  - group: main
    strip_idx: 9
    kind: column
    length: 300
    direction: up
    col: 105
  - group: main
    strip_idx: 10
    kind: column
    length: 300
    direction: down
    col: 106
  - group: main
    strip_idx: 11
    kind: column
    length: 300
    direction: up
    col: 107
  - group: main
    strip_idx: 12
    kind: column
    length: 300
    direction: down
    col: 108
  - group: main
    strip_idx: 13
    kind: column
    length: 300
    direction: up
    col: 109
  - group: main
    strip_idx: 14
    kind: column
    length: 300
    direction: down
    col: 110
  - group: main
    strip_idx: 15
    kind: column
    length: 300
    direction: up
    col: 111
  - group: main
    strip_idx: 16
    kind: column
    length: 300
    direction: down
    col: 112
  - group: main
    strip_idx: 17
    kind: column
    length: 300
    direction: up
    col: 113
  - group: main
    strip_idx: 18
    kind: column
    length: 300
    direction: down
    col: 114
  - group: main
    strip_idx: 19
    kind: column
    length: 300
    direction: up
    col: 115
  - group: main
    strip_idx: 20
    kind: column
    length: 300
    direction: down
    col: 116
  - group: main
    strip_idx: 21
    kind: column
    length: 300
    direction: up
    col: 117
  - group: main
    strip_idx: 22
    kind: column
    length: 300
    direction: down
    col: 118
  - group: main
    strip_idx: 23
    kind: column
    length: 300
    direction: up
    col: 119
  - group: main
    strip_idx: 24
    kind: column
    length: 300
    direction: down
    col: 120
  - group: main
    strip_idx: 25
    kind: column
    length: 300
    direction: up
    col: 121
  - group: main
    strip_idx: 26
    kind: column
    length: 300
    direction: down
    col: 122
  - group: main
    strip_idx: 27
    kind: column
    length: 300
    direction: up
    col: 123
  - group: main
    strip_idx: 28
    kind: column
    length: 300
    direction: down
    col: 124
  - group: main
    strip_idx: 29
    kind: column
    length: 300
    direction: up
    col: 125
  - group: main
    strip_idx: 30
    kind: column
    length: 300
    direction: down
    col: 126
  - group: main
    strip_idx: 31
    kind: column
    length: 300
    direction: up
    col: 127
- host: wol-7f928c.local
  protocol: ddp
  object_id: 4
  strips:
  - group: main
    strip_idx: 0
    kind: column
    length: 300
    direction: down
    col: 6
  - group: main
    strip_idx: 1
    kind: column
    length: 300
    direction: up
    col: 7
  - group: main
    strip_idx: 2
    kind: column
    length: 300
    direction: down
    col: 8
  - group: main
    strip_idx: 3
    kind: column
    length: 300
    direction: up
    col: 9
  - group: main
    strip_idx: 4
    kind: column
    length: 300
    direction: down
    col: 10
  - group: main
    strip_idx: 5
    kind: column
    length: 300
    direction: up
    col: 11
  - group: main
    strip_idx: 6
    kind: column
    length: 300
    direction: down
    col: 12
  - group: main
    strip_idx: 7
    kind: column
    length: 300
    direction: up
    col: 13
