import numpy as np
from enum import Enum

class WeatherState(Enum):
    CLEAR = "clear"
    LIGHT_RAIN = "light_rain"
    HEAVY_RAIN = "heavy_rain"
    THUNDERSTORM = "thunderstorm"
    WINDY_NIGHT = "windy_night"
    FOGGY = "foggy"
    HEAVY_FOG = "heavy_fog"
    SPOOKY = "spooky"
    FIREFLY = "firefly"
    SANDSTORM = "sandstorm"
    HURRICANE = "hurricane"
    ASTEROID = "asteroid"
    MUSHROOM = "mushroom"
    LEAVES = "leaves"
    BLOOM = "bloom"
    CYBER_NEON_DRIZZLE = "cyber_neon_drizzle"
    CYBER_DATA_STORM = "cyber_data_storm"
    CYBER_SMOG_HAZE = "cyber_smog_haze"
    CYBER_ELECTRIC_STORM = "cyber_electric_storm"
    CYBER_ACID_RAIN = "cyber_acid_rain"
    CYBER_HOLOGRAM_NIGHT = "cyber_hologram_night"
    CYBER_BLACKOUT = "cyber_blackout"
    CYBER_GLITCH_FOG = "cyber_glitch_fog"
    CYBER_NEON_CLEAR = "cyber_neon_clear"
    CYBER_DRONE_PATROL = "cyber_drone_patrol"
    # ── New states (cyberpunk scale-up) ─────────────────────────────────────
    CYBER_DAWN_PIRATE = "cyber_dawn_pirate"
    CYBER_CROWN_VAULT = "cyber_crown_vault"
    CYBER_MIDDEN_MARKET = "cyber_midden_market"
    CYBER_UNDERSIDE_FLOOD = "cyber_underside_flood"
    CYBER_HOUR_OF_STATIC = "cyber_hour_of_static"
    CYBER_AR_BLOOM = "cyber_ar_bloom"
    CYBER_TRANSIT_CORRIDOR = "cyber_transit_corridor"
    CYBER_RELAY_NODE = "cyber_relay_node"
    CYBER_BROADCAST_NIGHT = "cyber_broadcast_night"
    DESERT_BLAZING_NOON = "desert_blazing_noon"
    DESERT_DUSK_EMBERS = "desert_dusk_embers"
    DESERT_STARLIT_NIGHT = "desert_starlit_night"
    DESERT_OASIS_NIGHT = "desert_oasis_night"
    DESERT_DRY_THUNDERSTORM = "desert_dry_thunderstorm"
    DESERT_DUST_DEVIL = "desert_dust_devil"
    DESERT_HARMATTAN = "desert_harmattan"
    DESERT_METEOR_SHOWER = "desert_meteor_shower"
    DESERT_BLOOD_MOON = "desert_blood_moon"
    DESERT_PRE_DAWN = "desert_pre_dawn"
    DESERT_DAWN = "desert_dawn"
    DESERT_GOLDEN_MORNING = "desert_golden_morning"
    DESERT_TWILIGHT_BLUE = "desert_twilight_blue"
    DESERT_DAY_RAIN = "desert_day_rain"
    DESERT_NIGHT_RAIN = "desert_night_rain"
    OCEAN_CALM_SHALLOWS = "ocean_calm_shallows"
    OCEAN_CHOPPY_SURFACE = "ocean_choppy_surface"
    OCEAN_STORM_SURGE = "ocean_storm_surge"
    OCEAN_DEEP_CALM = "ocean_deep_calm"
    OCEAN_BIOLUMINESCENT_SWARM = "ocean_bioluminescent_swarm"
    OCEAN_ABYSS = "ocean_abyss"
    OCEAN_KELP_FOREST = "ocean_kelp_forest"
    OCEAN_CORAL_REEF = "ocean_coral_reef"
    OCEAN_JELLYFISH_BLOOM = "ocean_jellyfish_bloom"
    OCEAN_MIDNIGHT_OPEN_WATER = "ocean_midnight_open_water"
    OCEAN_MAELSTROM = "ocean_maelstrom"
    OCEAN_TIDE_POOL = "ocean_tide_pool"
    OCEAN_HYDROTHERMAL_VENT = "ocean_hydrothermal_vent"
    BARTIKI_DAWN = "bartiki_dawn"
    BARTIKI_MORNING_RUSH = "bartiki_morning_rush"
    BARTIKI_MIDDAY = "bartiki_midday"
    BARTIKI_AFTERNOON = "bartiki_afternoon"
    BARTIKI_EVENING_RUSH = "bartiki_evening_rush"
    BARTIKI_DUSK = "bartiki_dusk"
    BARTIKI_NIGHT = "bartiki_night"
    BARTIKI_LATE_NIGHT = "bartiki_late_night"
    BARTIKI_STORMY = "bartiki_stormy"
    BARTIKI_PRIDE = "bartiki_pride"
    LOVE_INFATUATION = "love_infatuation"
    LOVE_TENDERNESS = "love_tenderness"
    LOVE_LONGING = "love_longing"
    LOVE_DEVOTION = "love_devotion"
    LOVE_HEARTBREAK = "love_heartbreak"
    LOVE_REUNION = "love_reunion"
    LOVE_SOLITUDE = "love_solitude"
    FOREST_DAWN = "forest_dawn"
    FOREST_MORNING = "forest_morning"
    FOREST_MIDDAY = "forest_midday"
    FOREST_DUSK = "forest_dusk"
    FOREST_NIGHT = "forest_night"
    FOREST_LATE_NIGHT = "forest_late_night"
    FOREST_NIGHT_STORM = "forest_night_storm"
    SNOWFALL = "snowfall"
    FIRST_FROST = "first_frost"
    AUTUMN_BLAZE = "autumn_blaze"
    AURORA_GROVE = "aurora_grove"
    SPIRIT_GROVE = "spirit_grove"
    FOREST_STORM = "forest_storm"
    POLLEN_DRIFT = "pollen_drift"
    FOREST_GOLDEN_HOUR = "forest_golden_hour"
    FOREST_BIOLUMINESCENT = "forest_bioluminescent"
    FOREST_MISTY_DAWN = "forest_misty_dawn"
    FOREST_PRE_STORM = "forest_pre_storm"
    FOREST_BREEZY = "forest_breezy"
    FOREST_MIGRATION = "forest_migration"
    FOREST_FIREFLY = "forest_firefly"
    FOREST_DRIZZLE = "forest_drizzle"
    FOREST_THUNDERSHOWER = "forest_thundershower"
    FOREST_POST_RAIN = "forest_post_rain"
    FOREST_NIGHT_DRIZZLE = "forest_night_drizzle"
    FOREST_NIGHT_SQUALL = "forest_night_squall"
    TEST_RGB = "test_rgb"
    TEST_HUE_BIN = "test_hue_bin"

# Global parameters that are always available in every weather set
# These cannot be removed from sets but their values can be customized per weather state
GLOBAL_PARAMETERS = [
    "possible_transitions",
    "transition_weights",
    "transition_duration",
    "Sound_volume",
    "ARI",
    "fog",
    "fog_color",
    "season_preference",
    "Switch_rate",
    "on_transition_events",
]

# Available background events (always-active effects)
# This is the single source of truth for which events can be used as continuous background effects.
# Add new background-capable events here. They must also exist in Stories_OGL.py's event_map.
AVAILABLE_BACKGROUND_EVENTS = [
    'clouds',
    'firefly',
    'stars',
    'rain',
    'fog',
    'sandstorm',
    'fog_beings',
    'falling_leaves',
]

# Parameter definitions for the weather editor
# Defines the type and input configuration for each parameter
PARAMETER_DEFINITIONS = {
    'ARI': {'type': 'number', 'step': 1},
    'Aurora_probability': {'type': 'number', 'step': 0.1},
    'Owly': {'type': 'number', 'step': 0.1},
    'Sound_volume': {'type': 'number', 'step': 0.1},
    'Switch_rate': {'type': 'number', 'step': 0.1},
    'Weird': {'type': 'number', 'step': 0.1},
    'Wolfy': {'type': 'number', 'step': 0.1},
    'ambient_sound': {'type': 'text'},
    # Multiplier on forest_birds spawn rate (1.0 default, larger for
    # migration / flock-heavy states). Step 0.5 because step 0.05
    # would be needlessly fine for what's essentially a flock-size dial.
    'bird_density': {'type': 'number', 'step': 0.5},
    'bioluminescence': {'type': 'number', 'step': 0.05},
    'bubble_density': {'type': 'number', 'step': 0.05},
    'canopy_density': {'type': 'number', 'step': 0.05},
    'celestial_visibility': {'type': 'number', 'step': 0.1},
    # ── New cyberpunk shader-specific params ────────────────────────────
    'cyber_rain_color': {'type': 'array', 'length': 3},
    'cyber_signage_density': {'type': 'number', 'step': 0.05},
    'cyber_skyline_density': {'type': 'number', 'step': 0.05},
    'cyber_transit_intensity': {'type': 'number', 'step': 0.05},
    'cyber_underway_intensity': {'type': 'number', 'step': 0.05},
    'velocity_direction': {'type': 'array', 'length': 2},
    # ─────────────────────────────────────────────────────────────────────
    'dapple_strength': {'type': 'number', 'step': 0.05},
    'data_flow_rate': {'type': 'number', 'step': 0.05},
    'drone_activity': {'type': 'number', 'step': 0.05},
    'electric_interference': {'type': 'number', 'step': 0.05},
    'eye_density': {'type': 'number', 'step': 0.05},
    'firefly_density': {'type': 'number', 'step': 0.1},
    'fog': {'type': 'number', 'step': 0.05},
    'fog_color': {'type': 'array', 'length': 3},
    'frost_level': {'type': 'number', 'step': 0.05},
    'glitch_probability': {'type': 'number', 'step': 0.05},
    'godray_strength': {'type': 'number', 'step': 0.05},
    'hologram_density': {'type': 'number', 'step': 0.05},
    'kelp_density': {'type': 'number', 'step': 0.05},
    'light_pollution': {'type': 'number', 'step': 0.05},
    'lightning_probability': {'type': 'number', 'step': 0.05},
    'marine_life_activity': {'type': 'number', 'step': 0.05},
    'meteor_rate': {'type': 'number', 'step': 0.05},
    'neon_intensity': {'type': 'number', 'step': 0.05},
    'on_transition_events': {'type': 'event-list'},
    'pollution_level': {'type': 'number', 'step': 0.05},
    'possible_transitions': {'type': 'array-string'},
    'pride_intensity': {'type': 'number', 'step': 0.05},
    'rain_rate': {'type': 'number', 'step': 0.1},
    'rainbow_intensity': {'type': 'number', 'step': 0.05},
    'sand_density': {'type': 'number', 'step': 0.1},
    'scan_line_intensity': {'type': 'number', 'step': 0.05},
    'season_preference': {'type': 'number', 'step': 0.025},
    'skiptime': {'type': 'number', 'step': 0.5},
    'snow_rate': {'type': 'number', 'step': 0.05},
    'spookyness': {'type': 'number', 'step': 0.1},
    'spore_color': {'type': 'number', 'step': 0.05},
    'spore_density': {'type': 'number', 'step': 0.05},
    'starryness': {'type': 'number', 'step': 0.1},
    'stream_flow_rate': {'type': 'number', 'step': 0.05},
    'tide_level': {'type': 'number', 'step': 0.05},
    'train_density': {'type': 'number', 'step': 0.1},
    'train_speed': {'type': 'number', 'step': 0.5},
    'transition_duration': {'type': 'number', 'step': 1},
    'transition_weights': {'type': 'array-number'},
    'tree_prob': {'type': 'number', 'step': 0.1},
    'vent_activity': {'type': 'number', 'step': 0.05},
    'volcano_level': {'type': 'number', 'step': 0.1},
    'wave_amplitude': {'type': 'number', 'step': 0.05},
    'wave_speed': {'type': 'number', 'step': 0.05},
    'wind_speed': {'type': 'number', 'step': 0.1},
}

# Default weather parameters
DEFAULT_WEATHER_PARAMS = {
    "wind_speed": 0,
    "rain_rate": 0,
    "lightning_probability": 0,
    "starryness": 1.0,
    "spookyness": 0.0,
    "fog": 0.0,
    "fog_color": np.array([0.7, 0.7, 0.7]),
    "possible_transitions": ['light_rain', 'foggy', 'windy_night'],
    "transition_weights": [1.0, 2.0, 0.5],
    "transition_duration": 20.0,
    "celestial_visibility": 1.0,
    "firefly_density": 0.0,
    "Aurora_probability": 0.0,
    "Wolfy": 0.0,
    "Switch_rate": 1.0,
    "meteor_rate": 0.0,
    "volcano_level": 0.0,
    "sand_density": 0.0,
    "skiptime": 0.0,
    "tree_prob": 0.0,
    "Weird": 0.0,
    "Sound_volume": 1.0,
    "season_preference": 0.375,
    "ambient_sound": None,
    "ARI": 0.0,
}

# Weather presets
# Weather state parameters
WEATHER_PRESETS = {
    WeatherState.ASTEROID: {
        "ARI": 40,
        "Switch_rate": 3,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 1,
        "meteor_rate": 0.2,
        "possible_transitions": ["clear"],
        "season_preference": 0.875,
        "starryness": 1,
        "transition_weights": [1],
    },

    WeatherState.AURORA_GROVE: {
        "ARI": 40,
        "Aurora_probability": 1,
        "Owly": 0.3,
        "Sound_volume": 1.2,
        "Switch_rate": 0.6,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "canopy_density": 1,
        "celestial_visibility": 1,
        "firefly_density": 0.3,
        "fog": 0.1,
        "fog_color": np.array([0.05, 0.1, 0.2]),
        "meteor_rate": 0.3,
        "on_transition_events": [['aurora', 120, 0]],
        "possible_transitions": ["forest_late_night", "forest_night"],
        "season_preference": 0.02,
        "starryness": 1,
        "transition_duration": 30,
        "transition_weights": [1, 0.6],
        "tree_prob": 0.2,
        "wind_speed": 0.05,
    },

    WeatherState.AUTUMN_BLAZE: {
        "ARI": 30,
        "Sound_volume": 1.3,
        "Switch_rate": 0.65,
        "ambient_sound": "030822_leaves-rustling-in-wind-79518.mp3",
        "canopy_density": 0.85,
        "celestial_visibility": 0.45,
        "dapple_strength": 0.5,
        "fog": 0.15,
        "fog_color": np.array([0.85, 0.45, 0.2]),
        "godray_strength": 0.6,
        "on_transition_events": [['falling_leaves', 80, 0]],
        "possible_transitions": ["forest_dusk", "leaves"],
        "season_preference": 0.66,
        "starryness": 0.3,
        "transition_duration": 25,
        "transition_weights": [1, 0.6],
        "tree_prob": 0.7,
        "wind_speed": 0.45,
    },

    WeatherState.BARTIKI_AFTERNOON: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "ambient_sound": "01 Rain Light EDITED.wav",
        "celestial_visibility": 0,
        "fog": 0.05,
        "fog_color": np.array([0.15, 0.15, 0.25]),
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_evening_rush", "bartiki_stormy", "bartiki_pride"],
        "rain_rate": 0.2,
        "season_preference": 0.6,
        "starryness": 0,
        "train_density": 1,
        "train_speed": 8,
        "transition_duration": 20,
        "transition_weights": [1, 0.2, 0.1],
        "wind_speed": 0.2,
    },

    WeatherState.BARTIKI_DAWN: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "celestial_visibility": 0.3,
        "fog": 0.75,
        "fog_color": np.array([0.4, 0.25, 0.15]),
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_morning_rush", "bartiki_stormy"],
        "rain_rate": 0,
        "season_preference": 0.2,
        "starryness": 0.3,
        "train_density": 1,
        "train_speed": 4,
        "transition_duration": 20,
        "transition_weights": [1, 0.1],
        "wind_speed": 0.1,
    },

    WeatherState.BARTIKI_DUSK: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "celestial_visibility": 0.6,
        "fog": 0.2,
        "fog_color": np.array([0.15, 0.12, 0.2]),
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_night"],
        "rain_rate": 0,
        "season_preference": 0.8,
        "starryness": 0.4,
        "train_density": 1,
        "train_speed": 6,
        "transition_duration": 20,
        "transition_weights": [1],
        "wind_speed": 0.1,
    },

    WeatherState.BARTIKI_EVENING_RUSH: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "celestial_visibility": 0.2,
        "fog": 0.1,
        "fog_color": np.array([0.35, 0.2, 0.1]),
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_dusk", "bartiki_stormy"],
        "rain_rate": 0,
        "season_preference": 0.7,
        "starryness": 0,
        "train_density": 1,
        "train_speed": 10,
        "transition_duration": 20,
        "transition_weights": [1, 0.1],
        "wind_speed": 0.15,
    },

    WeatherState.BARTIKI_LATE_NIGHT: {
        "ARI": 0,
        "Switch_rate": 0.22,
        "celestial_visibility": 1,
        "fog": 0,
        "fog_color": np.array([0.03, 0.03, 0.1]),
        "meteor_rate": 0.8,
        "possible_transitions": ["bartiki_dawn"],
        "rain_rate": 0,
        "season_preference": 0.05,
        "starryness": 1,
        "train_density": 1,
        "train_speed": 2,
        "transition_duration": 20,
        "transition_weights": [1],
        "wind_speed": 0,
    },

    WeatherState.BARTIKI_MIDDAY: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "celestial_visibility": 0,
        "fog": 0,
        "fog_color": np.array([0.1, 0.1, 0.2]),
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_afternoon", "bartiki_stormy", "bartiki_pride"],
        "rain_rate": 0,
        "season_preference": 0.5,
        "starryness": 0,
        "train_density": 1,
        "train_speed": 8,
        "transition_duration": 20,
        "transition_weights": [1, 0.25, 0.1],
        "wind_speed": 0.15,
    },

    WeatherState.BARTIKI_MORNING_RUSH: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "celestial_visibility": 0,
        "fog": 0.6,
        "fog_color": np.array([0.1, 0.1, 0.2]),
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_midday", "bartiki_stormy", "bartiki_pride"],
        "rain_rate": 0,
        "season_preference": 0.3,
        "starryness": 0,
        "train_density": 1,
        "train_speed": 10,
        "transition_duration": 20,
        "transition_weights": [1, 0.25, 0.1],
        "wind_speed": 0.1,
    },

    WeatherState.BARTIKI_NIGHT: {
        "ARI": 0,
        "Switch_rate": 0.25,
        "celestial_visibility": 1,
        "fog": 0,
        "fog_color": np.array([0.05, 0.05, 0.15]),
        "meteor_rate": 0.5,
        "possible_transitions": ["bartiki_late_night", "bartiki_stormy"],
        "rain_rate": 0.1,
        "season_preference": 0.95,
        "starryness": 1,
        "train_density": 1,
        "train_speed": 4,
        "transition_duration": 20,
        "transition_weights": [1, 0.05],
        "wind_speed": 0.05,
    },

    WeatherState.BARTIKI_PRIDE: {
        "ARI": 25,
        "Switch_rate": 0.5,
        "celestial_visibility": 0,
        "fog": 0,
        "fog_color": np.array([1, 0.6, 0.9]),
        "lightning_probability": 0,
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_afternoon", "bartiki_evening_rush", "bartiki_dusk"],
        "pride_intensity": 1,
        "rain_rate": 0,
        "season_preference": 0.4,
        "starryness": 0,
        "train_density": 1.5,
        "train_speed": 6,
        "transition_duration": 30,
        "transition_weights": [1, 1, 0.8],
        "wind_speed": 0.35,
    },

    WeatherState.BARTIKI_STORMY: {
        "ARI": 30,
        "Switch_rate": 0.32,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "celestial_visibility": 0,
        "fog": 0.35,
        "fog_color": np.array([0.15, 0.15, 0.2]),
        "lightning_probability": 0.3,
        "meteor_rate": 0,
        "possible_transitions": ["bartiki_midday", "bartiki_afternoon", "bartiki_evening_rush", "bartiki_morning_rush"],
        "rain_rate": 0.8,
        "season_preference": 0.5,
        "starryness": 0,
        "train_density": 1,
        "train_speed": 5,
        "transition_duration": 20,
        "transition_weights": [1, 1, 0.8, 0.8],
        "wind_speed": 0.6,
    },

    WeatherState.BLOOM: {
        "ARI": 45,
        "Aurora_probability": 0,
        "Sound_volume": 1,
        "Switch_rate": 1,
        "Weird": 0,
        "ambient_sound": "09 Nightingale.mp3",
        "canopy_density": 0.85,
        "firefly_density": 0.5,
        "fog": 0,
        "meteor_rate": 0.05,
        "possible_transitions": ["clear", "windy_night", "leaves", "firefly", "mushroom", "pollen_drift"],
        "rain_rate": 0,
        "season_preference": 0.5,
        "skiptime": 0,
        "transition_weights": [1, 0.25, 1, 1, 0.5, 0.8],
        "tree_prob": 0.1,
        "wind_speed": 0.2,
    },

    WeatherState.CLEAR: {
        "ARI": 40,
        "Aurora_probability": 0.5,
        "Switch_rate": 0.9,
        "Weird": 1,
        "ambient_sound": "Forest Cicadas EDITED.wav",
        "canopy_density": 0.8,
        "meteor_rate": 0.25,
        "possible_transitions": ["light_rain", "foggy", "windy_night", "firefly", "mushroom", "leaves", "bloom", "forest_morning", "desert_blazing_noon", "desert_dusk_embers", "desert_starlit_night", "desert_dust_devil", "desert_meteor_shower"],
        "season_preference": 0.375,
        "transition_weights": [1, 1, 0.75, 0.5, 0.2, 0.75, 0.75, 0.8, 1, 0.6, 0.5, 0.4, 0.2],
        "tree_prob": 1,
        "wind_speed": 0.2,
    },

    WeatherState.CYBER_ACID_RAIN: {
        "ARI": 42,
        "ambient_sound": "Rain, Metallic Shelter.mp3",
        "celestial_visibility": 0,
        "cyber_rain_color": np.array([0.55, 1.00, 0.20]),   # acid green
        "fog": 0.6,
        "fog_color": np.array([0.5, 0.8, 0.2]),
        "light_pollution": 0.5,
        "neon_intensity": 0.5,
        "pollution_level": 0.8,
        "possible_transitions": ["cyber_smog_haze", "cyber_neon_drizzle", "cyber_electric_storm"],
        "rain_rate": 0.7,
        "season_preference": 0.7,
        "starryness": 0,
        "transition_weights": [1, 1.2, 0.6],
    },

    WeatherState.CYBER_BLACKOUT: {
        "ARI": 35,
        "ambient_sound": "Wind Strong EDITED.wav",
        "celestial_visibility": 0.8,
        "cyber_signage_density": 0.0,        # no neon signage during a blackout
        "cyber_skyline_density": 0.0,        # only the shader's 5% emergency-lights baseline
        "fog": 0.3,
        "fog_color": np.array([0.1, 0.1, 0.15]),
        "glitch_probability": 0.2,
        "hologram_density": 0,
        "light_pollution": 0.1,
        "neon_intensity": 0,
        "possible_transitions": ["cyber_neon_clear", "cyber_smog_haze", "cyber_glitch_fog"],
        "season_preference": 0.9,
        "starryness": 0.9,
        "transition_weights": [1.5, 0.5, 0.3],
    },

    WeatherState.CYBER_DATA_STORM: {
        "ARI": 40,
        "ambient_sound": "Rain, Metallic Shelter.mp3",
        "celestial_visibility": 0,
        "data_flow_rate": 1,
        "electric_interference": 0.7,
        "fog": 0.3,
        "fog_color": np.array([0, 1, 0.3]),
        "glitch_probability": 0.5,
        "light_pollution": 0.5,
        "neon_intensity": 0.6,
        "possible_transitions": ["cyber_electric_storm", "cyber_glitch_fog", "cyber_neon_drizzle"],
        "season_preference": 0.5,
        "starryness": 0,
        "transition_weights": [0.8, 0.6, 1],
    },

    WeatherState.CYBER_DRONE_PATROL: {
        "ARI": 38,
        "ambient_sound": "Vent Air Industrial.mp3",
        "celestial_visibility": 0.3,
        "drone_activity": 1,
        "fog": 0.2,
        "fog_color": np.array([0.2, 0.2, 0.3]),
        "hologram_density": 0.2,
        "light_pollution": 0.7,
        "neon_intensity": 0.6,
        "possible_transitions": ["cyber_neon_clear", "cyber_hologram_night", "cyber_blackout"],
        "scan_line_intensity": 0.3,
        "season_preference": 0.4,
        "starryness": 0.4,
        "transition_weights": [1, 0.8, 0.3],
    },

    WeatherState.CYBER_ELECTRIC_STORM: {
        "ARI": 38,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "celestial_visibility": 0,
        "cyber_rain_color": np.array([0.30, 0.55, 1.00]),   # electric blue
        "electric_interference": 1,
        "fog": 0.4,
        "fog_color": np.array([0, 0.5, 1]),
        "glitch_probability": 0.3,
        "light_pollution": 0.4,
        "lightning_probability": 1,
        "neon_intensity": 0.3,
        "possible_transitions": ["cyber_data_storm", "cyber_acid_rain", "cyber_neon_drizzle"],
        "rain_rate": 0.5,
        "season_preference": 0.85,
        "starryness": 0,
        "transition_weights": [0.5, 0.8, 1],
    },

    WeatherState.CYBER_GLITCH_FOG: {
        "ARI": 36,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "celestial_visibility": 0,
        "data_flow_rate": 0.4,
        "electric_interference": 0.6,
        "fog": 0.8,
        "fog_color": np.array([0.6, 0, 0.6]),
        "glitch_probability": 0.8,
        "light_pollution": 0.6,
        "neon_intensity": 0.7,
        "possible_transitions": ["cyber_data_storm", "cyber_hologram_night", "cyber_neon_drizzle"],
        "season_preference": 0.25,
        "starryness": 0,
        "transition_weights": [0.7, 0.5, 1],
    },

    WeatherState.CYBER_HOLOGRAM_NIGHT: {
        "ARI": 40,
        "ambient_sound": "Constant Walla of about 1000 People.mp3",
        "celestial_visibility": 0.2,
        "drone_activity": 0.5,
        "fog": 0.1,
        "fog_color": np.array([0.3, 0.1, 0.5]),
        "hologram_density": 1,
        "light_pollution": 0.9,
        "neon_intensity": 0.8,
        "possible_transitions": ["cyber_neon_clear", "cyber_drone_patrol", "cyber_glitch_fog"],
        "season_preference": 0,
        "starryness": 0.3,
        "transition_weights": [1.2, 0.8, 0.4],
    },

    WeatherState.CYBER_NEON_CLEAR: {
        "ARI": 45,
        "ambient_sound": "room_interior_traffic.mp3",
        "celestial_visibility": 0.1,
        "fog": 0.1,
        "fog_color": np.array([0.2, 0.1, 0.4]),
        "hologram_density": 0.3,
        "light_pollution": 1,
        "neon_intensity": 1,
        "on_transition_events": [['pixel_spots', 60, 0]],
        "possible_transitions": ["cyber_neon_drizzle", "cyber_hologram_night", "cyber_drone_patrol", "cyber_smog_haze"],
        "season_preference": 0.2,
        "starryness": 0.2,
        "transition_weights": [1.5, 1, 0.8, 0.5],
    },

    WeatherState.CYBER_NEON_DRIZZLE: {
        "ARI": 35,
        "ambient_sound": "Rain Heavy Rain On Concrete and Wood.mp3",
        "celestial_visibility": 0.05,
        "cyber_rain_color": np.array([0.20, 0.95, 1.00]),   # neon cyan
        "cyber_signage_density": 0.55,     # wet streets glow with signage
        "cyber_skyline_density": 0.55,     # buildings present
        "data_flow_rate": 0.15,            # subtle data
        "fog": 0.2,
        "fog_color": np.array([0.1, 0.3, 0.6]),
        "hologram_density": 0.35,          # some holograms catch the rain
        "light_pollution": 0.8,
        "neon_intensity": 0.9,
        "on_transition_events": [['sunrise', 60, 0]],
        "pollution_level": 0.30,           # damp wet smog visible
        "possible_transitions": ["cyber_neon_clear", "cyber_acid_rain", "cyber_data_storm"],
        "rain_rate": 0.3,
        "scan_line_intensity": 0.40,       # cyan scan-line accents
        "season_preference": 0.15,
        "starryness": 0.1,
        "transition_weights": [1.5, 0.5, 0.3],
    },

    WeatherState.CYBER_SMOG_HAZE: {
        "ARI": 50,
        "ambient_sound": "Vent Air Industrial.mp3",
        "celestial_visibility": 0.1,
        "fog": 0.9,
        "fog_color": np.array([0.7, 0.5, 0.2]),
        "light_pollution": 0.6,
        "neon_intensity": 0.4,
        "pollution_level": 1,
        "possible_transitions": ["cyber_acid_rain", "cyber_blackout", "cyber_neon_clear"],
        "season_preference": 0.6,
        "starryness": 0,
        "transition_weights": [0.7, 0.3, 1.2],
    },

    # ─────────────────────────────────────────────────────────────────────
    # New cyberpunk states (scale-up)
    # ─────────────────────────────────────────────────────────────────────

    WeatherState.CYBER_DAWN_PIRATE: {
        "ARI": 50,
        "ambient_sound": "room_interior_traffic.mp3",
        "celestial_visibility": 0.2,
        "cyber_signage_density": 0.55,    # amber-tinted signs through smog
        "cyber_skyline_density": 0.75,    # solid building silhouettes
        "data_flow_rate": 0.15,
        "drone_activity": 0.08,            # rare drone presence at dawn
        "fog": 0.55,                       # heavier dawn smog
        "fog_color": np.array([0.85, 0.45, 0.15]),   # vivid sodium amber (was muted)
        "hologram_density": 0.3,
        "light_pollution": 0.55,
        "neon_intensity": 0.5,
        "pollution_level": 0.55,           # strong amber smog
        "possible_transitions": ["cyber_broadcast_night", "cyber_neon_clear", "cyber_midden_market"],
        "scan_line_intensity": 0.35,
        "season_preference": 0.18,
        "starryness": 0.1,
        "transition_weights": [1.2, 1.0, 0.5],
    },

    WeatherState.CYBER_CROWN_VAULT: {
        "ARI": 60,
        "ambient_sound": "server room.mp3",
        "celestial_visibility": 0.0,
        "cyber_signage_density": 0.10,
        "cyber_skyline_density": 0.95,    # absolute max — wall of towers
        "data_flow_rate": 0.55,            # corporate data streams everywhere
        "drone_activity": 0.45,            # frequent surveillance drones
        "fog": 0.15,
        "fog_color": np.array([0.10, 0.18, 0.35]),  # cold cyan-blue (was washed)
        "hologram_density": 0.65,          # corporate billboards everywhere
        "light_pollution": 0.55,           # more sky band brightness
        "neon_intensity": 0.30,
        "pollution_level": 0.15,           # slight sterile haze
        "possible_transitions": ["cyber_relay_node", "cyber_drone_patrol", "cyber_hologram_night", "cyber_ar_bloom"],
        "scan_line_intensity": 0.85,       # heavy corporate-display scan lines
        "season_preference": 0.5,
        "starryness": 0.0,
        "transition_weights": [0.8, 0.6, 1.0, 0.3],
    },

    WeatherState.CYBER_MIDDEN_MARKET: {
        "ARI": 30,
        "ambient_sound": "Constant Walla of about 1000 People.mp3",
        "celestial_visibility": 0.0,
        "cyber_signage_density": 1.0,       # absolute max — every storefront lit
        "cyber_skyline_density": 0.85,      # dense building cluster
        "data_flow_rate": 0.35,
        "drone_activity": 0.15,
        "fog": 0.40,
        "fog_color": np.array([0.55, 0.30, 0.20]),  # warm food-stall smog
        "hologram_density": 0.65,           # crowded advertising
        "light_pollution": 0.85,            # everywhere brightness
        "neon_intensity": 1.0,              # neon at full
        "pollution_level": 0.55,            # crowded street smog
        "possible_transitions": ["cyber_neon_clear", "cyber_neon_drizzle", "cyber_broadcast_night", "cyber_smog_haze"],
        "scan_line_intensity": 0.4,
        "season_preference": 0.7,
        "starryness": 0.0,
        "transition_weights": [1.2, 0.8, 0.6, 0.6],
    },

    WeatherState.CYBER_UNDERSIDE_FLOOD: {
        "ARI": 45,
        "ambient_sound": "underwater_turbulent.mp3",
        "celestial_visibility": 0.0,
        "cyber_signage_density": 0.0,
        "cyber_skyline_density": 0.0,
        "cyber_underway_intensity": 1.0,
        "data_flow_rate": 0.0,
        "drone_activity": 0.0,
        "fog": 0.45,
        "fog_color": np.array([0.05, 0.35, 0.45]),   # vivid teal
        "hologram_density": 0.0,
        "light_pollution": 0.10,
        "neon_intensity": 0.0,
        "pollution_level": 0.30,                     # was 0.75 — was washing out flood features
        "possible_transitions": ["cyber_relay_node", "cyber_broadcast_night", "cyber_blackout"],
        "scan_line_intensity": 0.0,
        "season_preference": 0.5,
        "starryness": 0.0,
        "transition_weights": [0.6, 0.8, 0.3],
    },

    WeatherState.CYBER_HOUR_OF_STATIC: {
        "ARI": 40,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 0.5,
        "cyber_signage_density": 0.45,             # signs visible but unanimated
        "cyber_skyline_density": 0.75,             # buildings strongly visible
        "data_flow_rate": 0.0,
        "drone_activity": 0.0,
        "fog": 0.20,
        "fog_color": np.array([0.30, 0.20, 0.45]), # vivid violet-night (was muddy)
        "glitch_probability": 0.0,
        "hologram_density": 0.0,                   # no AR overlays during static
        "light_pollution": 0.40,                   # natural city glow
        "neon_intensity": 0.55,                    # neon still on, just unsupervised
        "pollution_level": 0.40,
        "possible_transitions": ["cyber_neon_clear", "cyber_midden_market", "cyber_dawn_pirate"],
        "scan_line_intensity": 0.0,
        "season_preference": 0.85,
        "starryness": 0.85,                        # stars actually visible (max)
        "transition_weights": [1.0, 1.0, 0.5],
    },

    WeatherState.CYBER_AR_BLOOM: {
        "ARI": 45,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "celestial_visibility": 0.1,
        "cyber_signage_density": 0.5,
        "cyber_skyline_density": 0.7,
        "data_flow_rate": 0.4,
        "drone_activity": 0.2,
        "electric_interference": 0.5,
        "fog": 0.35,
        "fog_color": np.array([0.30, 0.10, 0.45]),
        "glitch_probability": 0.9,
        "hologram_density": 1.0,
        "light_pollution": 0.55,
        "neon_intensity": 0.7,
        "pollution_level": 0.25,
        "possible_transitions": ["cyber_glitch_fog", "cyber_hologram_night", "cyber_data_storm"],
        "scan_line_intensity": 0.8,
        "season_preference": 0.4,
        "starryness": 0.1,
        "transition_weights": [1.0, 0.8, 0.7],
    },

    WeatherState.CYBER_TRANSIT_CORRIDOR: {
        "ARI": 35,
        "ambient_sound": "Train sounds.mp3",
        "celestial_visibility": 0.0,
        "cyber_signage_density": 0.0,         # no street signs inside a tunnel
        "cyber_skyline_density": 0.0,         # no buildings inside a tunnel
        "cyber_transit_intensity": 1.0,
        "data_flow_rate": 0.20,
        "drone_activity": 0.0,
        "fog": 0.30,
        "fog_color": np.array([0.10, 0.20, 0.55]),  # cool tunnel blue
        "hologram_density": 0.0,              # no holograms in a tunnel
        "light_pollution": 0.2,
        "neon_intensity": 0.3,                # subtle floor grid only
        "pollution_level": 0.40,              # interior haze
        "possible_transitions": ["cyber_underside_flood", "cyber_midden_market", "cyber_neon_clear"],
        "scan_line_intensity": 0.65,          # heavy CRT — this IS a HUD view
        "season_preference": 0.5,
        "starryness": 0.0,
        "transition_weights": [0.7, 1.0, 1.0],
    },

    WeatherState.CYBER_RELAY_NODE: {
        "ARI": 55,
        "ambient_sound": "server room.mp3",
        "celestial_visibility": 0.0,
        "cyber_signage_density": 0.0,
        "cyber_skyline_density": 0.0,
        "data_flow_rate": 1.0,
        "drone_activity": 0.05,
        "fog": 0.4,
        "fog_color": np.array([0.05, 0.10, 0.20]),
        "hologram_density": 0.4,
        "light_pollution": 0.15,
        "neon_intensity": 0.4,
        "pollution_level": 0.2,
        "possible_transitions": ["cyber_crown_vault", "cyber_data_storm", "cyber_glitch_fog", "cyber_underside_flood"],
        "scan_line_intensity": 0.95,
        "season_preference": 0.0,
        "starryness": 0.0,
        "transition_weights": [0.7, 1.0, 0.6, 0.4],
    },

    WeatherState.CYBER_BROADCAST_NIGHT: {
        "ARI": 35,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 0.3,
        "cyber_signage_density": 0.4,
        "cyber_skyline_density": 0.55,
        "data_flow_rate": 0.2,
        "drone_activity": 0.1,
        "fog": 0.45,
        "fog_color": np.array([0.45, 0.30, 0.15]),
        "hologram_density": 0.15,
        "light_pollution": 0.5,
        "neon_intensity": 0.6,
        "pollution_level": 0.55,
        "possible_transitions": ["cyber_dawn_pirate", "cyber_midden_market", "cyber_smog_haze", "cyber_underside_flood"],
        "scan_line_intensity": 0.55,
        "season_preference": 0.92,
        "starryness": 0.2,
        "transition_weights": [1.0, 0.8, 0.7, 0.5],
    },

    WeatherState.DESERT_BLAZING_NOON: {
        "ARI": 45,
        "Switch_rate": 0.8,
        "ambient_sound": "High Desert Crickets.wav",
        "celestial_visibility": 1,
        "fog": 0.15,
        "fog_color": np.array([0.9, 0.85, 0.6]),
        "possible_transitions": ["sandstorm", "desert_dust_devil", "desert_dusk_embers", "desert_harmattan", "desert_golden_morning", "desert_day_rain"],
        "sand_density": 0.05,
        "season_preference": 0.5,
        "starryness": 0,
        "transition_weights": [0.4, 0.4, 0.8, 0.3, 0.3, 0.25],
        "wind_speed": 0.2,
    },

    WeatherState.DESERT_BLOOD_MOON: {
        "ARI": 14,
        "Switch_rate": 0.6,
        "Wolfy": 0.5,
        "ambient_sound": "294 Spooky Ghostly Moans (5) EDITED.wav",
        "celestial_visibility": 0.8,
        "firefly_density": 0.2,
        "fog": 0.4,
        "fog_color": np.array([0.6, 0.1, 0.1]),
        "possible_transitions": ["desert_starlit_night", "desert_pre_dawn", "spooky", "windy_night", "desert_meteor_shower", "volcano"],
        "season_preference": 0.95,
        "spookyness": 0.6,
        "starryness": 0.6,
        "transition_weights": [0.6, 0.5, 0.4, 0.4, 0.2, 0.15],
        "wind_speed": 0.2,
    },

    WeatherState.DESERT_DAWN: {
        "ARI": 35,
        "Switch_rate": 0.5,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 1,
        "fog": 0.2,
        "fog_color": np.array([0.85, 0.55, 0.5]),
        "on_transition_events": [],
        "possible_transitions": ["desert_golden_morning", "desert_pre_dawn", "desert_harmattan"],
        "season_preference": 0.22,
        "starryness": 0.2,
        "transition_duration": 25,
        "transition_weights": [1, 0.3, 0.4],
        "wind_speed": 0.15,
    },

    WeatherState.DESERT_DAY_RAIN: {
        "ARI": 30,
        "Sound_volume": 1.4,
        "Switch_rate": 0.9,
        "ambient_sound": "01 Rain Light EDITED.wav",
        "celestial_visibility": 0.35,
        "fog": 0.4,
        "fog_color": np.array([0.55, 0.5, 0.45]),
        "lightning_probability": 0.1,
        "possible_transitions": ["desert_blazing_noon", "desert_harmattan", "desert_dust_devil", "sandstorm", "desert_dry_thunderstorm", "desert_golden_morning"],
        "rain_rate": 0.55,
        "sand_density": 0.1,
        "season_preference": 0.42,
        "starryness": 0,
        "transition_weights": [0.7, 0.5, 0.4, 0.4, 0.3, 0.4],
        "wind_speed": 0.8,
    },

    WeatherState.DESERT_DRY_THUNDERSTORM: {
        "ARI": 25,
        "Sound_volume": 1.5,
        "Switch_rate": 1.2,
        "ambient_sound": "Wind Strong EDITED.wav",
        "celestial_visibility": 0.3,
        "fog": 0.45,
        "fog_color": np.array([0.5, 0.4, 0.3]),
        "lightning_probability": 0.8,
        "possible_transitions": ["sandstorm", "windy_night", "desert_dust_devil", "clear", "volcano", "desert_day_rain", "desert_night_rain"],
        "rain_rate": 0,
        "sand_density": 0.3,
        "season_preference": 0.8,
        "starryness": 0.2,
        "transition_weights": [0.6, 0.5, 0.4, 0.3, 0.2, 0.5, 0.5],
        "wind_speed": 0.9,
    },

    WeatherState.DESERT_DUSK_EMBERS: {
        "ARI": 35,
        "Switch_rate": 0.7,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 0.8,
        "fog": 0.35,
        "fog_color": np.array([0.85, 0.4, 0.2]),
        "on_transition_events": [],
        "possible_transitions": ["desert_twilight_blue", "desert_starlit_night", "desert_oasis_night", "windy_night", "desert_blood_moon"],
        "season_preference": 0.7,
        "starryness": 0.3,
        "transition_duration": 25,
        "transition_weights": [1, 0.5, 0.4, 0.3, 0.15],
        "wind_speed": 0.4,
    },

    WeatherState.DESERT_DUST_DEVIL: {
        "ARI": 30,
        "Switch_rate": 1.5,
        "ambient_sound": "26 Heavy Wind Gusts Blowing Sand EDITED.wav",
        "celestial_visibility": 0.7,
        "fog": 0.25,
        "fog_color": np.array([0.75, 0.65, 0.45]),
        "on_transition_events": [['vortex', 30, 0]],
        "possible_transitions": ["sandstorm", "desert_blazing_noon", "desert_harmattan", "desert_golden_morning"],
        "sand_density": 0.5,
        "season_preference": 0.55,
        "starryness": 0.1,
        "transition_weights": [0.6, 0.5, 0.4, 0.3],
        "wind_speed": 1.2,
    },

    WeatherState.DESERT_GOLDEN_MORNING: {
        "ARI": 30,
        "Switch_rate": 0.6,
        "ambient_sound": "High Desert Crickets.wav",
        "celestial_visibility": 1,
        "fog": 0.1,
        "fog_color": np.array([0.95, 0.75, 0.5]),
        "possible_transitions": ["desert_blazing_noon", "desert_harmattan", "desert_dawn", "desert_dust_devil"],
        "season_preference": 0.33,
        "starryness": 0,
        "transition_weights": [1, 0.7, 0.4, 0.4],
        "wind_speed": 0.2,
    },

    WeatherState.DESERT_HARMATTAN: {
        "ARI": 40,
        "Sound_volume": 1.3,
        "Switch_rate": 0.5,
        "ambient_sound": "Wind Strong EDITED.wav",
        "celestial_visibility": 0.4,
        "fog": 0.55,
        "fog_color": np.array([0.7, 0.55, 0.3]),
        "possible_transitions": ["sandstorm", "desert_blazing_noon", "windy_night", "desert_dust_devil", "desert_golden_morning", "desert_day_rain"],
        "sand_density": 0.6,
        "season_preference": 0.45,
        "starryness": 0.2,
        "transition_weights": [0.5, 0.4, 0.4, 0.3, 0.4, 0.3],
        "wind_speed": 1,
    },

    WeatherState.DESERT_METEOR_SHOWER: {
        "ARI": 40,
        "Switch_rate": 0.7,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 1,
        "fog": 0,
        "fog_color": np.array([0.1, 0.1, 0.2]),
        "meteor_rate": 0.4,
        "possible_transitions": ["desert_starlit_night", "desert_pre_dawn", "asteroid", "windy_night", "desert_blood_moon"],
        "season_preference": 0.95,
        "starryness": 1,
        "transition_weights": [1, 0.5, 0.4, 0.3, 0.2],
        "wind_speed": 0.1,
    },

    WeatherState.DESERT_NIGHT_RAIN: {
        "ARI": 35,
        "Sound_volume": 1.3,
        "Switch_rate": 0.7,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "celestial_visibility": 0.1,
        "fog": 0.45,
        "fog_color": np.array([0.18, 0.22, 0.32]),
        "lightning_probability": 0.2,
        "possible_transitions": ["desert_starlit_night", "desert_oasis_night", "desert_pre_dawn", "desert_blood_moon", "desert_dry_thunderstorm", "windy_night"],
        "rain_rate": 0.65,
        "season_preference": 0.93,
        "spookyness": 0.1,
        "starryness": 0,
        "transition_weights": [0.7, 0.5, 0.5, 0.3, 0.3, 0.4],
        "wind_speed": 0.5,
    },

    WeatherState.DESERT_OASIS_NIGHT: {
        "ARI": 30,
        "Switch_rate": 0.5,
        "ambient_sound": "High Desert Crickets.wav",
        "celestial_visibility": 0.9,
        "firefly_density": 0.6,
        "fog": 0.1,
        "fog_color": np.array([0.2, 0.2, 0.35]),
        "possible_transitions": ["desert_starlit_night", "desert_pre_dawn", "desert_dusk_embers", "windy_night", "desert_blood_moon", "desert_night_rain"],
        "season_preference": 0.9,
        "starryness": 0.8,
        "transition_weights": [1, 0.6, 0.4, 0.3, 0.2, 0.25],
        "wind_speed": 0.15,
    },

    WeatherState.DESERT_PRE_DAWN: {
        "ARI": 50,
        "Switch_rate": 0.4,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 1,
        "fog": 0.05,
        "fog_color": np.array([0.1, 0.12, 0.2]),
        "possible_transitions": ["desert_dawn", "desert_starlit_night", "desert_oasis_night"],
        "season_preference": 0.08,
        "starryness": 0.7,
        "transition_weights": [1, 0.4, 0.3],
        "wind_speed": 0.05,
    },

    WeatherState.DESERT_STARLIT_NIGHT: {
        "ARI": 50,
        "Switch_rate": 0.5,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 1,
        "fog": 0,
        "fog_color": np.array([0.1, 0.12, 0.25]),
        "meteor_rate": 0.05,
        "possible_transitions": ["desert_meteor_shower", "desert_oasis_night", "windy_night", "desert_blood_moon", "desert_dusk_embers", "desert_pre_dawn", "desert_night_rain"],
        "season_preference": 0.95,
        "starryness": 1,
        "transition_weights": [0.4, 0.6, 0.5, 0.2, 0.4, 0.7, 0.25],
        "wind_speed": 0.1,
    },

    WeatherState.DESERT_TWILIGHT_BLUE: {
        "ARI": 35,
        "Switch_rate": 0.5,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 0.5,
        "fog": 0.2,
        "fog_color": np.array([0.15, 0.2, 0.45]),
        "possible_transitions": ["desert_starlit_night", "desert_oasis_night", "windy_night", "desert_dusk_embers", "desert_blood_moon"],
        "season_preference": 0.83,
        "starryness": 0.4,
        "transition_weights": [1, 0.6, 0.5, 0.3, 0.2],
        "wind_speed": 0.3,
    },

    WeatherState.FIREFLY: {
        "ARI": 35,
        "Sound_volume": 2,
        "Weird": 0.5,
        "Wolfy": 0.2,
        "ambient_sound": "High Desert Crickets.wav",
        "canopy_density": 0.7,
        "celestial_visibility": 0.8,
        "firefly_density": 1,
        "fog": 0.3,
        "meteor_rate": 0.05,
        "possible_transitions": ["clear", "foggy", "spooky", "heavy_fog", "bloom", "light_rain", "forest_late_night"],
        "season_preference": 0.3,
        "skiptime": 2,
        "spookyness": 0.05,
        "transition_weights": [1, 0.5, 0.1, 0.1, 0.25, 0.25, 0.8],
        "tree_prob": 0.2,
        "wind_speed": 0.2,
    },

    WeatherState.FIRST_FROST: {
        "ARI": 35,
        "Sound_volume": 1,
        "Switch_rate": 0.6,
        "ambient_sound": "wind_in_pines.mp3",
        "canopy_density": 0.55,
        "celestial_visibility": 0.5,
        "fog": 0.35,
        "fog_color": np.array([0.6, 0.7, 0.85]),
        "frost_level": 1,
        "godray_strength": 0.7,
        "possible_transitions": ["forest_dawn", "snowfall"],
        "season_preference": 0.18,
        "snow_rate": 0.15,
        "starryness": 0.4,
        "transition_duration": 25,
        "transition_weights": [1, 0.4],
        "tree_prob": 0.4,
        "wind_speed": 0.1,
    },

    WeatherState.FOGGY: {
        "ARI": 40,
        "Sound_volume": 0.6,
        "Weird": 0.5,
        "ambient_sound": "25 Swamp Ambience 2 Special Mix Light Chorus of Frogs Croa EDITED.wav",
        "canopy_density": 0.6,
        "celestial_visibility": 0.5,
        "firefly_density": 0.05,
        "fog": 0.7,
        "fog_color": np.array([0.3, 0.8, 0.3]),
        "possible_transitions": ["clear", "light_rain", "spooky", "firefly", "heavy_fog", "mushroom", "first_frost", "forest_dawn"],
        "rain_rate": 0.05,
        "season_preference": 0.15,
        "spookyness": 0.05,
        "starryness": 0.8,
        "transition_weights": [0.9, 0.1, 0.1, 0.5, 0.35, 0.1, 0.6, 0.6],
        "tree_prob": 0.2,
        "wind_speed": 0.1,
    },

    WeatherState.FOREST_BIOLUMINESCENT: {
        "ARI": 30,
        "Owly": 0.6,
        "Sound_volume": 1.4,
        "Switch_rate": 1,
        "Wolfy": 0.2,
        "ambient_sound": "25 Swamp Ambience 2 Special Mix Light Chorus of Frogs Croa EDITED.wav",
        "canopy_density": 0.55,
        "celestial_visibility": 0.7,
        "dapple_strength": 0,
        "eye_density": 0.85,
        "firefly_density": 0.3,
        "fog": 0.12,
        "fog_color": np.array([0.04, 0.1, 0.14]),
        "meteor_rate": 0,
        "possible_transitions": ["forest_late_night", "spirit_grove", "forest_firefly"],
        "season_preference": 0.05,
        "spore_color": 0,
        "spore_density": 0.5,
        "starryness": 1,
        "transition_duration": 20,
        "transition_weights": [1, 0.3, 0.5],
        "tree_prob": 0.2,
        "wind_speed": 0.05,
    },

    WeatherState.FOREST_BREEZY: {
        "ARI": 30,
        "Sound_volume": 1.1,
        "Switch_rate": 0.7,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "canopy_density": 1,
        "celestial_visibility": 0,
        "dapple_strength": 0.7,
        "fog": 0.08,
        "fog_color": np.array([0.45, 0.55, 0.55]),
        "godray_strength": 0.55,
        "possible_transitions": ["forest_midday", "forest_morning", "forest_pre_storm"],
        "season_preference": 0.5,
        "starryness": 0,
        "transition_duration": 22,
        "transition_weights": [1, 0.7, 0.3],
        "tree_prob": 0.8,
        "wind_speed": 1.4,
    },

    WeatherState.FOREST_DAWN: {
        "ARI": 35,
        "Sound_volume": 1,
        "Switch_rate": 0.6,
        "ambient_sound": "21. Wren Sings - Bird.flac",
        "canopy_density": 0.85,
        "celestial_visibility": 0.4,
        "dapple_strength": 0.2,
        "fog": 0.45,
        "fog_color": np.array([0.55, 0.45, 0.35]),
        "godray_strength": 0.85,
        "possible_transitions": ["forest_morning", "first_frost", "pollen_drift", "forest_misty_dawn"],
        "season_preference": 0.22,
        "starryness": 0.25,
        "transition_duration": 25,
        "transition_weights": [1, 0.25, 0.4, 0.6],
        "tree_prob": 0.6,
        "wind_speed": 0.15,
    },

    WeatherState.FOREST_DRIZZLE: {
        "ARI": 30,
        "Sound_volume": 1.2,
        "Switch_rate": 0.6,
        "ambient_sound": "01 Rain Light EDITED.wav",
        "canopy_density": 0.85,
        "celestial_visibility": 0.5,
        "dapple_strength": 0.25,
        "fog": 0.25,
        "fog_color": np.array([0.5, 0.58, 0.55]),
        "godray_strength": 0.35,
        "lightning_probability": 0,
        "on_transition_events": [['rain_on_leaves', 60, 0]],
        "possible_transitions": ["forest_morning", "forest_midday", "forest_storm", "forest_post_rain"],
        "rain_rate": 0.3,
        "season_preference": 0.42,
        "starryness": 0,
        "transition_duration": 22,
        "transition_weights": [0.7, 0.6, 0.5, 0.8],
        "tree_prob": 0.6,
        "wind_speed": 0.35,
    },

    WeatherState.FOREST_DUSK: {
        "ARI": 35,
        "Sound_volume": 1,
        "Switch_rate": 0.6,
        "ambient_sound": "Swamp Crickets.wav",
        "canopy_density": 0.9,
        "celestial_visibility": 0.55,
        "dapple_strength": 0.45,
        "fog": 0.3,
        "fog_color": np.array([0.5, 0.32, 0.25]),
        "godray_strength": 0.95,
        "possible_transitions": ["forest_night", "autumn_blaze", "forest_night_storm", "forest_golden_hour", "forest_firefly"],
        "season_preference": 0.78,
        "starryness": 0.35,
        "transition_duration": 25,
        "transition_weights": [1, 0.3, 0.4, 0.5, 0.4],
        "tree_prob": 0.5,
        "wind_speed": 0.2,
    },

    WeatherState.FOREST_FIREFLY: {
        "ARI": 32,
        "Owly": 0.5,
        "Sound_volume": 1.2,
        "Switch_rate": 0.6,
        "ambient_sound": "Forest Cicadas EDITED.wav",
        "canopy_density": 0.7,
        "celestial_visibility": 0.4,
        "dapple_strength": 0,
        "eye_density": 0.4,
        "firefly_density": 1,
        "fog": 0.1,
        "fog_color": np.array([0.1, 0.14, 0.2]),
        "possible_transitions": ["forest_night", "forest_late_night", "forest_bioluminescent"],
        "season_preference": 0.82,
        "starryness": 0.85,
        "transition_duration": 28,
        "transition_weights": [1, 0.5, 0.7],
        "tree_prob": 0.5,
        "wind_speed": 0.12,
    },

    WeatherState.FOREST_GOLDEN_HOUR: {
        "ARI": 30,
        "Sound_volume": 1,
        "Switch_rate": 0.7,
        "ambient_sound": "03 Forest Ambience 3 Distant Birds and Frogs With a Few Cl.mp3",
        "canopy_density": 1,
        "celestial_visibility": 0,
        "dapple_strength": 1,
        "fog": 0.12,
        "fog_color": np.array([0.85, 0.55, 0.25]),
        "godray_strength": 1,
        "possible_transitions": ["forest_dusk", "forest_midday", "autumn_blaze"],
        "season_preference": 0.7,
        "starryness": 0,
        "transition_duration": 25,
        "transition_weights": [1, 0.6, 0.5],
        "tree_prob": 1,
        "wind_speed": 0.2,
    },

    WeatherState.FOREST_LATE_NIGHT: {
        "ARI": 32,
        "Owly": 0.7,
        "Sound_volume": 1.5,
        "Switch_rate": 0.6,
        "Wolfy": 0.4,
        "ambient_sound": "Owls Hooting.wav",
        "canopy_density": 0.65,
        "celestial_visibility": 1,
        "eye_density": 0.7,
        "firefly_density": 0.4,
        "fog": 0.15,
        "fog_color": np.array([0.05, 0.07, 0.18]),
        "meteor_rate": 0.2,
        "possible_transitions": ["forest_dawn", "aurora_grove", "spirit_grove", "snowfall", "forest_night_storm", "forest_bioluminescent", "forest_firefly", "forest_night_drizzle"],
        "season_preference": 0.06,
        "starryness": 1,
        "transition_duration": 30,
        "transition_weights": [1, 0.3, 0.25, 0.2, 0.3, 0.5, 0.5, 0.5],
        "tree_prob": 0.2,
        "wind_speed": 0.05,
    },

    WeatherState.FOREST_MIDDAY: {
        "ARI": 30,
        "Sound_volume": 1,
        "Switch_rate": 0.8,
        "ambient_sound": "03 Forest Ambience 3 Distant Birds and Frogs With a Few Cl.mp3",
        "canopy_density": 1,
        "celestial_visibility": 0,
        "dapple_strength": 0.85,
        "fog": 0.05,
        "fog_color": np.array([0.4, 0.6, 0.4]),
        "godray_strength": 0.7,
        "possible_transitions": ["forest_dusk", "forest_storm", "autumn_blaze", "forest_breezy", "forest_migration", "forest_golden_hour", "forest_drizzle", "forest_thundershower"],
        "season_preference": 0.5,
        "starryness": 0,
        "transition_duration": 25,
        "transition_weights": [1, 0.3, 0.4, 0.4, 0.3, 0.4, 0.5, 0.3],
        "tree_prob": 1,
        "wind_speed": 0.25,
    },

    WeatherState.FOREST_MIGRATION: {
        "ARI": 28,
        "Sound_volume": 1.3,
        "Switch_rate": 0.65,
        "ambient_sound": "03 Forest Ambience 3 Distant Birds and Frogs With a Few Cl.mp3",
        "bird_density": 6,
        "canopy_density": 0.7,
        "celestial_visibility": 0,
        "dapple_strength": 0.6,
        "fog": 0.06,
        "fog_color": np.array([0.55, 0.65, 0.55]),
        "godray_strength": 0.6,
        "possible_transitions": ["forest_midday", "forest_morning", "forest_dusk"],
        "season_preference": 0.45,
        "starryness": 0,
        "transition_duration": 22,
        "transition_weights": [1, 0.7, 0.4],
        "tree_prob": 0.9,
        "wind_speed": 0.45,
    },

    WeatherState.FOREST_MISTY_DAWN: {
        "ARI": 30,
        "Sound_volume": 1.2,
        "Switch_rate": 0.6,
        "ambient_sound": "09 Nightingale.mp3",
        "canopy_density": 0.85,
        "celestial_visibility": 0.4,
        "dapple_strength": 0.5,
        "fog": 0.65,
        "fog_color": np.array([0.55, 0.62, 0.7]),
        "godray_strength": 0.75,
        "possible_transitions": ["forest_dawn", "forest_morning", "forest_golden_hour"],
        "season_preference": 0.22,
        "starryness": 0.15,
        "transition_duration": 28,
        "transition_weights": [1, 0.7, 0.4],
        "tree_prob": 0.6,
        "wind_speed": 0.1,
    },

    WeatherState.FOREST_MORNING: {
        "ARI": 30,
        "Sound_volume": 1.2,
        "Switch_rate": 0.7,
        "ambient_sound": "01 Brook.mp3",
        "canopy_density": 1,
        "celestial_visibility": 0,
        "dapple_strength": 0.55,
        "fog": 0.25,
        "fog_color": np.array([0.45, 0.55, 0.42]),
        "godray_strength": 1,
        "possible_transitions": ["forest_midday", "forest_storm", "pollen_drift", "forest_misty_dawn", "forest_migration", "forest_breezy", "forest_drizzle"],
        "season_preference": 0.42,
        "starryness": 0,
        "transition_duration": 25,
        "transition_weights": [1, 0.25, 0.5, 0.4, 0.4, 0.3, 0.5],
        "tree_prob": 0.8,
        "wind_speed": 0.2,
    },

    WeatherState.FOREST_NIGHT: {
        "ARI": 35,
        "Owly": 0.5,
        "Sound_volume": 1.4,
        "Switch_rate": 0.6,
        "Wolfy": 0.2,
        "ambient_sound": "Forest Cicadas EDITED.wav",
        "canopy_density": 0.75,
        "celestial_visibility": 0.95,
        "firefly_density": 0.7,
        "fog": 0.25,
        "fog_color": np.array([0.1, 0.12, 0.22]),
        "possible_transitions": ["forest_late_night", "aurora_grove", "spirit_grove", "forest_night_storm", "forest_firefly", "forest_bioluminescent"],
        "season_preference": 0.94,
        "starryness": 1,
        "transition_duration": 25,
        "transition_weights": [1, 0.4, 0.3, 0.4, 0.6, 0.5],
        "tree_prob": 0.3,
        "wind_speed": 0.1,
    },

    WeatherState.FOREST_NIGHT_DRIZZLE: {
        "ARI": 30,
        "Owly": 0.3,
        "Sound_volume": 1,
        "Switch_rate": 0.6,
        "ambient_sound": "01 Rain Light EDITED.wav",
        "canopy_density": 0.7,
        "celestial_visibility": 0.5,
        "dapple_strength": 0,
        "fog": 0.3,
        "fog_color": np.array([0.1, 0.14, 0.2]),
        "godray_strength": 0,
        "lightning_probability": 0,
        "on_transition_events": [['rain_on_leaves', 80, 0]],
        "possible_transitions": ["forest_night", "forest_late_night", "forest_night_squall", "forest_night_storm"],
        "rain_rate": 0.3,
        "season_preference": 0.92,
        "starryness": 1,
        "transition_duration": 24,
        "transition_weights": [1, 0.8, 0.6, 0.4],
        "tree_prob": 0.4,
        "wind_speed": 0.25,
    },

    WeatherState.FOREST_NIGHT_SQUALL: {
        "ARI": 30,
        "Owly": 0.1,
        "Sound_volume": 1.6,
        "Switch_rate": 0.8,
        "ambient_sound": "rain_on_leaves.mp3",
        "canopy_density": 0.7,
        "celestial_visibility": 0.1,
        "dapple_strength": 0,
        "fog": 0.5,
        "fog_color": np.array([0.1, 0.14, 0.2]),
        "godray_strength": 0,
        "lightning_probability": 0.3,
        "on_transition_events": [['lightning', 6, 0], ['rain_on_leaves', 90, 0]],
        "possible_transitions": ["forest_night_storm", "forest_night_drizzle", "forest_night", "forest_late_night"],
        "rain_rate": 0.65,
        "season_preference": 0.94,
        "spookyness": 0.1,
        "starryness": 1,
        "transition_duration": 22,
        "transition_weights": [0.7, 0.7, 0.6, 0.4],
        "tree_prob": 0.45,
        "wind_speed": 1.2,
    },

    WeatherState.FOREST_NIGHT_STORM: {
        "ARI": 28,
        "Owly": 0.3,
        "Sound_volume": 2.5,
        "Switch_rate": 0.6,
        "Weird": 0.1,
        "Wolfy": 0.3,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "canopy_density": 0.7,
        "celestial_visibility": 0,
        "dapple_strength": 0,
        "fog": 0.7,
        "fog_color": np.array([0.03, 0.04, 0.07]),
        "godray_strength": 0,
        "lightning_probability": 0.7,
        "on_transition_events": [['lightning', 6, 0], ['lightning', 6, 8], ['lightning', 6, 18], ['rain_on_leaves', 120, 0]],
        "possible_transitions": ["forest_late_night", "forest_night", "forest_night_squall", "forest_storm", "forest_night_drizzle"],
        "rain_rate": 1,
        "season_preference": 0.9,
        "spookyness": 0.3,
        "starryness": 1,
        "transition_duration": 25,
        "transition_weights": [1, 0.8, 0.7, 0.4, 0.6],
        "tree_prob": 0.5,
        "wind_speed": 1.3,
    },

    WeatherState.FOREST_POST_RAIN: {
        "ARI": 30,
        "Sound_volume": 0.1,
        "Switch_rate": 1,
        "ambient_sound": "Rain Into Puddle EDITED.wav",
        "canopy_density": 0.95,
        "celestial_visibility": 0.6,
        "dapple_strength": 0.9,
        "fog": 0.3,
        "fog_color": np.array([0.65, 0.72, 0.62]),
        "godray_strength": 0.95,
        "possible_transitions": ["forest_midday", "forest_golden_hour", "forest_morning", "forest_misty_dawn"],
        "rain_rate": 0,
        "season_preference": 0.5,
        "starryness": 0,
        "transition_duration": 28,
        "transition_weights": [1, 0.7, 0.6, 0.3],
        "tree_prob": 0.8,
        "wind_speed": 0.2,
    },

    WeatherState.FOREST_PRE_STORM: {
        "ARI": 32,
        "Sound_volume": 0.9,
        "Switch_rate": 0.95,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "canopy_density": 0.9,
        "celestial_visibility": 0.15,
        "dapple_strength": 0,
        "fog": 0.4,
        "fog_color": np.array([0.35, 0.4, 0.42]),
        "godray_strength": 0,
        "possible_transitions": ["forest_storm", "forest_night_storm", "forest_midday"],
        "season_preference": 0.55,
        "spookyness": 0.25,
        "starryness": 0.2,
        "transition_duration": 18,
        "transition_weights": [1.4, 0.6, 0.2],
        "tree_prob": 0.5,
        "wind_speed": 0.05,
    },

    WeatherState.FOREST_STORM: {
        "ARI": 30,
        "Sound_volume": 1.8,
        "Switch_rate": 0.7,
        "ambient_sound": "rain_on_leaves.mp3",
        "canopy_density": 0.75,
        "celestial_visibility": 0.1,
        "dapple_strength": 0,
        "fog": 0.55,
        "fog_color": np.array([0.25, 0.3, 0.35]),
        "godray_strength": 0,
        "lightning_probability": 0.5,
        "on_transition_events": [['lightning', 6, 0], ['rain_on_leaves', 90, 0]],
        "possible_transitions": ["forest_morning", "forest_midday", "forest_pre_storm", "forest_night_storm"],
        "rain_rate": 0.7,
        "season_preference": 0.55,
        "starryness": 0,
        "transition_duration": 25,
        "transition_weights": [0.8, 0.8, 0.6, 0.5],
        "tree_prob": 0.4,
        "wind_speed": 0.9,
    },

    WeatherState.FOREST_THUNDERSHOWER: {
        "ARI": 28,
        "Sound_volume": 1.8,
        "Switch_rate": 1.5,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "canopy_density": 0.8,
        "celestial_visibility": 0.05,
        "dapple_strength": 0,
        "fog": 0.5,
        "fog_color": np.array([0.3, 0.35, 0.4]),
        "godray_strength": 0,
        "lightning_probability": 1,
        "on_transition_events": [['lightning', 6, 0], ['lightning', 6, 8], ['rain_on_leaves', 60, 0]],
        "possible_transitions": ["forest_post_rain", "forest_storm", "forest_midday"],
        "rain_rate": 0.95,
        "season_preference": 0.55,
        "starryness": 0,
        "transition_duration": 18,
        "transition_weights": [1.2, 0.5, 0.4],
        "tree_prob": 0.5,
        "wind_speed": 1.1,
    },

    WeatherState.HEAVY_FOG: {
        "ARI": 26,
        "Sound_volume": 6,
        "Switch_rate": 0.75,
        "Weird": -0.3,
        "Wolfy": 0.2,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "celestial_visibility": 0.25,
        "firefly_density": 2,
        "fog": 1.25,
        "fog_color": np.array([0.6, 0, 0.6]),
        "on_transition_events": [['fog_beings', 80, 0]],
        "possible_transitions": ["spooky", "firefly", "mushroom"],
        "rain_rate": 0,
        "season_preference": 0.175,
        "spookyness": 0,
        "starryness": 0.2,
        "transition_weights": [0.1, 0.75, 0.2],
        "tree_prob": 0.05,
        "wind_speed": 0,
    },

    WeatherState.HEAVY_RAIN: {
        "ARI": 39,
        "Sound_volume": 2,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "celestial_visibility": 0.3,
        "fog": 0.5,
        "fog_color": np.array([0.3, 0.3, 0.7]),
        "lightning_probability": 0.1,
        "possible_transitions": ["light_rain", "thunderstorm", "windy_night", "hurricane"],
        "rain_rate": 0.8,
        "season_preference": 0.7,
        "skiptime": 2,
        "starryness": 0.1,
        "transition_weights": [2, 1, 0.5, 0.3],
        "tree_prob": 0.2,
        "wind_speed": 0.7,
    },

    WeatherState.HURRICANE: {
        "ARI": 100,
        "Sound_volume": 3,
        "Switch_rate": 2,
        "Wolfy": 0.2,
        "ambient_sound": "Hurricane_1.mp3",
        "celestial_visibility": 0,
        "fog": 0.6,
        "fog_color": np.array([0.35, 0.42, 0.28]),
        "lightning_probability": 0.8,
        "on_transition_events": [['hurricane', 50, 0], ['lightning', 6, 0], ['lightning', 6, 5], ['lightning', 6, 12]],
        "possible_transitions": ["thunderstorm", "heavy_rain", "windy_night"],
        "rain_rate": 1,
        "season_preference": 0.95,
        "skiptime": 2,
        "spookyness": 0.15,
        "starryness": 0,
        "transition_weights": [1.5, 1, 0.5],
        "tree_prob": 0.3,
        "wind_speed": 2.2,
    },

    WeatherState.LEAVES: {
        "ARI": 25,
        "Aurora_probability": 0,
        "Sound_volume": 2,
        "Switch_rate": 1,
        "Weird": 0,
        "ambient_sound": "030822_leaves-rustling-in-wind-79518.mp3",
        "canopy_density": 0.7,
        "fog": 0.25,
        "meteor_rate": 0,
        "on_transition_events": [['falling_leaves', 60, 0]],
        "possible_transitions": ["clear", "windy_night", "spooky", "autumn_blaze"],
        "rain_rate": 0.2,
        "season_preference": 0.7,
        "skiptime": 2,
        "transition_weights": [1, 1, 0.25, 0.8],
        "tree_prob": 0,
        "wind_speed": 0.4,
    },

    WeatherState.LIGHT_RAIN: {
        "ARI": 29,
        "Sound_volume": 2,
        "ambient_sound": "01 Rain Light EDITED.wav",
        "canopy_density": 0.75,
        "celestial_visibility": 0.8,
        "fog": 0.1,
        "fog_color": np.array([0.2, 0.5, 0.5]),
        "possible_transitions": ["clear", "heavy_rain", "foggy", "bloom", "forest_storm"],
        "rain_rate": 0.2,
        "season_preference": 0.125,
        "skiptime": 0,
        "starryness": 0.5,
        "transition_weights": [1, 1.2, 0.5, 0.25, 0.8],
        "tree_prob": 0.2,
        "wind_speed": 0.4,
    },

    WeatherState.LOVE_DEVOTION: {
        "ARI": 60,
        "Switch_rate": 0.5,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "celestial_visibility": 0.5,
        "fog": 0.2,
        "fog_color": np.array([0.85, 0.7, 0.4]),
        "possible_transitions": ["love_tenderness", "love_solitude", "love_longing"],
        "season_preference": 0.5,
        "starryness": 0.6,
        "transition_weights": [1, 0.8, 0.4],
        "wind_speed": 0.05,
    },

    WeatherState.LOVE_HEARTBREAK: {
        "ARI": 50,
        "Switch_rate": 0.9,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 0.3,
        "fog": 0.6,
        "fog_color": np.array([0.15, 0.18, 0.4]),
        "possible_transitions": ["love_solitude", "love_longing"],
        "season_preference": 0.95,
        "starryness": 0.5,
        "transition_weights": [1.2, 0.8],
        "wind_speed": 0.4,
    },

    WeatherState.LOVE_INFATUATION: {
        "ARI": 30,
        "Switch_rate": 1.5,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "celestial_visibility": 0.4,
        "fog": 0.15,
        "fog_color": np.array([0.7, 0.35, 0.45]),
        "possible_transitions": ["love_tenderness", "love_longing", "love_solitude"],
        "season_preference": 0.3,
        "starryness": 0.6,
        "transition_weights": [1.2, 0.6, 0.4],
        "wind_speed": 0.2,
    },

    WeatherState.LOVE_LONGING: {
        "ARI": 50,
        "Switch_rate": 0.8,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "celestial_visibility": 0.9,
        "fog": 0.45,
        "fog_color": np.array([0.25, 0.3, 0.55]),
        "possible_transitions": ["love_heartbreak", "love_solitude", "love_reunion", "love_tenderness"],
        "season_preference": 0.85,
        "starryness": 1,
        "transition_weights": [0.6, 0.9, 0.5, 0.7],
        "wind_speed": 0.3,
    },

    WeatherState.LOVE_REUNION: {
        "ARI": 35,
        "Switch_rate": 1.2,
        "ambient_sound": "09 Nightingale.mp3",
        "celestial_visibility": 0.8,
        "fog": 0.1,
        "fog_color": np.array([1, 0.55, 0.4]),
        "possible_transitions": ["love_devotion", "love_tenderness", "love_infatuation"],
        "season_preference": 0.4,
        "starryness": 0.8,
        "transition_weights": [1.2, 1, 0.5],
        "wind_speed": 0.15,
    },

    WeatherState.LOVE_SOLITUDE: {
        "ARI": 55,
        "Switch_rate": 0.6,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "celestial_visibility": 1,
        "fog": 0.15,
        "fog_color": np.array([0.2, 0.2, 0.35]),
        "possible_transitions": ["love_tenderness", "love_longing", "love_devotion", "love_infatuation"],
        "season_preference": 0,
        "starryness": 1,
        "transition_weights": [0.8, 0.6, 0.7, 0.4],
        "wind_speed": 0.05,
    },

    WeatherState.LOVE_TENDERNESS: {
        "ARI": 45,
        "Switch_rate": 0.7,
        "ambient_sound": "09 Nightingale.mp3",
        "celestial_visibility": 0.6,
        "fog": 0.25,
        "fog_color": np.array([0.9, 0.6, 0.65]),
        "possible_transitions": ["love_devotion", "love_infatuation", "love_solitude"],
        "season_preference": 0.45,
        "starryness": 0.7,
        "transition_weights": [1.2, 0.7, 0.5],
        "wind_speed": 0.05,
    },

    WeatherState.MUSHROOM: {
        "ARI": 22,
        "Aurora_probability": 0.5,
        "Switch_rate": 1,
        "Weird": 0,
        "ambient_sound": "Frog Croaks.wav",
        "canopy_density": 0.7,
        "fog": 0.5,
        "meteor_rate": 0,
        "possible_transitions": ["clear", "foggy", "heavy_fog", "leaves", "bloom", "spirit_grove"],
        "rain_rate": 0.1,
        "season_preference": 0.5,
        "transition_weights": [1, 1, 0.25, 0.5, 0.25, 0.7],
        "tree_prob": 1,
        "wind_speed": 0,
    },

    WeatherState.OCEAN_ABYSS: {
        "ARI": 60,
        "ambient_sound": "Low Wind & Tone Atmosphere.wav",
        "bioluminescence": 0.8,
        "bubble_density": 0,
        "fog": 0.95,
        "fog_color": np.array([0.02, 0.02, 0.08]),
        "kelp_density": 0,
        "marine_life_activity": 0.1,
        "possible_transitions": ["ocean_deep_calm", "ocean_bioluminescent_swarm", "ocean_hydrothermal_vent"],
        "season_preference": 0,
        "tide_level": 1,
        "transition_weights": [1, 0.5, 0.6],
        "wave_amplitude": 0.05,
        "wave_speed": 0.1,
        "wind_speed": 0.05,
    },

    WeatherState.OCEAN_BIOLUMINESCENT_SWARM: {
        "ARI": 50,
        "ambient_sound": "280 Water - Processed long big ocean wave whoosh by x5.mp3",
        "bioluminescence": 1,
        "bubble_density": 0.1,
        "fog": 0.3,
        "fog_color": np.array([0.15, 0.25, 0.4]),
        "kelp_density": 0,
        "marine_life_activity": 1,
        "possible_transitions": ["ocean_deep_calm", "ocean_calm_shallows", "ocean_kelp_forest", "ocean_jellyfish_bloom"],
        "season_preference": 0.875,
        "tide_level": 1,
        "transition_weights": [0.8, 1, 0.6, 0.7],
        "wave_amplitude": 0.2,
        "wave_speed": 0.3,
        "wind_speed": 0.1,
    },

    WeatherState.OCEAN_CALM_SHALLOWS: {
        "ARI": 50,
        "ambient_sound": "285 Water - Natural long small ocean wave by x5.mp3",
        "bioluminescence": 0.2,
        "bubble_density": 0.1,
        "fog": 0.1,
        "fog_color": np.array([0.3, 0.6, 0.9]),
        "kelp_density": 0.3,
        "marine_life_activity": 0.7,
        "possible_transitions": ["ocean_kelp_forest", "ocean_coral_reef", "ocean_choppy_surface", "ocean_midnight_open_water", "ocean_tide_pool"],
        "season_preference": 0.15,
        "tide_level": 0.65,
        "transition_weights": [1, 1, 0.5, 0.4, 0.7],
        "wave_amplitude": 0.3,
        "wave_speed": 0.4,
        "wind_speed": 0.2,
    },

    WeatherState.OCEAN_CHOPPY_SURFACE: {
        "ARI": 45,
        "ambient_sound": "46 Waves 2 Medium Size Waves Crash & Close Out with Foam H.mp3",
        "bioluminescence": 0,
        "bubble_density": 0.8,
        "fog": 0.4,
        "fog_color": np.array([0.2, 0.4, 0.6]),
        "kelp_density": 0.1,
        "marine_life_activity": 0.2,
        "possible_transitions": ["ocean_storm_surge", "ocean_calm_shallows", "ocean_deep_calm", "ocean_maelstrom", "ocean_midnight_open_water"],
        "season_preference": 0.55,
        "tide_level": 0.9,
        "transition_weights": [0.8, 1.2, 0.5, 0.4, 0.3],
        "wave_amplitude": 0.8,
        "wave_speed": 0.6,
        "wind_speed": 0.8,
    },

    WeatherState.OCEAN_CORAL_REEF: {
        "ARI": 58,
        "ambient_sound": "underwater_turbulent.mp3",
        "bioluminescence": 0.1,
        "bubble_density": 1,
        "fog": 0.15,
        "fog_color": np.array([0.25, 0.65, 0.95]),
        "kelp_density": 0,
        "marine_life_activity": 1,
        "on_transition_events": [['coral', 120, 0]],
        "possible_transitions": ["ocean_calm_shallows", "ocean_kelp_forest", "ocean_choppy_surface"],
        "season_preference": 0.2,
        "tide_level": 0.7,
        "transition_weights": [1.2, 0.8, 0.3],
        "wave_amplitude": 0.25,
        "wave_speed": 0.35,
        "wind_speed": 0.2,
    },

    WeatherState.OCEAN_DEEP_CALM: {
        "ARI": 45,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "bioluminescence": 0.6,
        "bubble_density": 0,
        "fog": 0.6,
        "fog_color": np.array([0.1, 0.2, 0.35]),
        "kelp_density": 0,
        "marine_life_activity": 0.4,
        "possible_transitions": ["ocean_bioluminescent_swarm", "ocean_abyss", "ocean_calm_shallows", "ocean_choppy_surface", "ocean_jellyfish_bloom", "ocean_hydrothermal_vent"],
        "season_preference": 0.95,
        "tide_level": 1,
        "transition_weights": [0.8, 0.3, 1, 0.6, 0.5, 0.4],
        "wave_amplitude": 0.2,
        "wave_speed": 0.3,
        "wind_speed": 0,
    },

    WeatherState.OCEAN_HYDROTHERMAL_VENT: {
        "ARI": 55,
        "ambient_sound": "underwater_turbulent.mp3",
        "bioluminescence": 0.55,
        "bubble_density": 1,
        "fog": 0.85,
        "fog_color": np.array([0.18, 0.08, 0.05]),
        "kelp_density": 0,
        "marine_life_activity": 0.25,
        "possible_transitions": ["ocean_abyss", "ocean_deep_calm"],
        "season_preference": 0,
        "tide_level": 1,
        "transition_weights": [1, 0.6],
        "vent_activity": 1,
        "wave_amplitude": 0.05,
        "wave_speed": 0.1,
        "wind_speed": 0.05,
    },

    WeatherState.OCEAN_JELLYFISH_BLOOM: {
        "ARI": 45,
        "ambient_sound": "280 Water - Processed long big ocean wave whoosh by x5.mp3",
        "bioluminescence": 0.65,
        "bubble_density": 0.05,
        "fog": 0.5,
        "fog_color": np.array([0.3, 0.1, 0.45]),
        "kelp_density": 0,
        "marine_life_activity": 0.4,
        "on_transition_events": [['tentacle', 120, 0]],
        "possible_transitions": ["ocean_deep_calm", "ocean_bioluminescent_swarm", "ocean_calm_shallows"],
        "season_preference": 0.1,
        "tide_level": 1,
        "transition_weights": [1, 0.8, 0.5],
        "wave_amplitude": 0.15,
        "wave_speed": 0.15,
        "wind_speed": 0.1,
    },

    WeatherState.OCEAN_KELP_FOREST: {
        "ARI": 42,
        "ambient_sound": "10 Sea from cliff top.mp3",
        "bioluminescence": 0.1,
        "bubble_density": 0.2,
        "fog": 0.25,
        "fog_color": np.array([0.2, 0.5, 0.3]),
        "kelp_density": 1,
        "marine_life_activity": 0.8,
        "possible_transitions": ["ocean_calm_shallows", "ocean_coral_reef", "ocean_choppy_surface"],
        "season_preference": 0.35,
        "tide_level": 0.6,
        "transition_weights": [1, 1, 0.4],
        "wave_amplitude": 0.5,
        "wave_speed": 0.5,
        "wind_speed": 0.3,
    },

    WeatherState.OCEAN_MAELSTROM: {
        "ARI": 45,
        "ambient_sound": "hurricane.mp3",
        "bioluminescence": 0,
        "bubble_density": 0.9,
        "fog": 0.65,
        "fog_color": np.array([0.15, 0.25, 0.35]),
        "kelp_density": 0,
        "marine_life_activity": 0,
        "on_transition_events": [['vortex', 90, 0]],
        "possible_transitions": ["ocean_storm_surge", "ocean_deep_calm"],
        "season_preference": 0.8,
        "tide_level": 0.85,
        "transition_weights": [1.2, 0.4],
        "wave_amplitude": 1.2,
        "wave_speed": 1.2,
        "wind_speed": 2,
    },

    WeatherState.OCEAN_MIDNIGHT_OPEN_WATER: {
        "ARI": 40,
        "ambient_sound": "285 Water - Natural long small ocean wave by x5.mp3",
        "bioluminescence": 0.3,
        "bubble_density": 0,
        "fog": 0.05,
        "fog_color": np.array([0.05, 0.08, 0.2]),
        "kelp_density": 0,
        "marine_life_activity": 0.1,
        "on_transition_events": [['stars', 180, 0]],
        "possible_transitions": ["ocean_calm_shallows", "ocean_choppy_surface"],
        "season_preference": 0,
        "tide_level": 0.5,
        "transition_weights": [1.2, 0.5],
        "wave_amplitude": 0.2,
        "wave_speed": 0.3,
        "wind_speed": 0.2,
    },

    WeatherState.OCEAN_STORM_SURGE: {
        "ARI": 38,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "bioluminescence": 0,
        "bubble_density": 1,
        "fog": 0.7,
        "fog_color": np.array([0.2, 0.35, 0.45]),
        "kelp_density": 0,
        "marine_life_activity": 0.05,
        "possible_transitions": ["ocean_choppy_surface", "ocean_deep_calm", "ocean_maelstrom"],
        "season_preference": 0.7,
        "tide_level": 0.6,
        "transition_weights": [1.5, 0.5, 0.6],
        "wave_amplitude": 1,
        "wave_speed": 1,
        "wind_speed": 1.5,
    },

    WeatherState.OCEAN_TIDE_POOL: {
        "ARI": 50,
        "ambient_sound": "285 Water - Natural long small ocean wave by x5.mp3",
        "bioluminescence": 0.05,
        "bubble_density": 0.3,
        "fog": 0.05,
        "fog_color": np.array([0.45, 0.75, 0.85]),
        "kelp_density": 0.15,
        "marine_life_activity": 1,
        "possible_transitions": ["ocean_calm_shallows", "ocean_coral_reef", "ocean_kelp_forest"],
        "season_preference": 0.25,
        "tide_level": 0,
        "transition_weights": [1.2, 0.7, 0.5],
        "wave_amplitude": 0.1,
        "wave_speed": 0.2,
        "wind_speed": 0.15,
    },

    WeatherState.POLLEN_DRIFT: {
        "ARI": 35,
        "Sound_volume": 1,
        "Switch_rate": 1,
        "ambient_sound": "09 Nightingale.mp3",
        "canopy_density": 0.9,
        "celestial_visibility": 0.2,
        "fog": 0.2,
        "fog_color": np.array([0.85, 0.7, 0.35]),
        "godray_strength": 0.75,
        "possible_transitions": ["forest_midday", "bloom", "forest_morning"],
        "season_preference": 0.34,
        "spore_color": 1,
        "spore_density": 0.85,
        "starryness": 0,
        "transition_duration": 25,
        "transition_weights": [1, 0.6, 0.5],
        "tree_prob": 0.6,
        "wind_speed": 0.3,
    },

    WeatherState.SANDSTORM: {
        "ARI": 30,
        "Switch_rate": 1.5,
        "ambient_sound": "26 Heavy Wind Gusts Blowing Sand EDITED.wav",
        "celestial_visibility": 0.6,
        "fog": 0.65,
        "fog_color": np.array([0.6, 0.5, 0.35]),
        "on_transition_events": [['sandstorm', 100, 0]],
        "possible_transitions": ["clear", "windy_night", "spooky", "firefly", "desert_dust_devil", "desert_harmattan", "desert_blazing_noon", "desert_dry_thunderstorm", "volcano"],
        "sand_density": 1,
        "season_preference": 0.6,
        "starryness": 0.25,
        "transition_weights": [0.3, 0.5, 0.1, 0.1, 0.7, 0.8, 0.4, 0.4, 0.15],
        "wind_speed": 2,
    },

    WeatherState.SNOWFALL: {
        "ARI": 28,
        "Sound_volume": 1.2,
        "Switch_rate": 0.75,
        "ambient_sound": "Wind Strong EDITED.wav",
        "canopy_density": 0.45,
        "celestial_visibility": 0.4,
        "fog": 0.55,
        "fog_color": np.array([0.7, 0.75, 0.85]),
        "frost_level": 0.7,
        "possible_transitions": ["first_frost", "forest_late_night"],
        "season_preference": 0.1,
        "snow_rate": 0.8,
        "starryness": 0.5,
        "transition_duration": 25,
        "transition_weights": [1, 0.5],
        "tree_prob": 0.3,
        "wind_speed": 0.4,
    },

    WeatherState.SPIRIT_GROVE: {
        "ARI": 28,
        "Owly": 0.4,
        "Sound_volume": 1.6,
        "Switch_rate": 1,
        "Weird": 0.6,
        "Wolfy": 0.5,
        "ambient_sound": "Tinkle Atmosphere 01.wav",
        "canopy_density": 0.55,
        "celestial_visibility": 0.4,
        "eye_density": 1,
        "firefly_density": 0.5,
        "fog": 0.85,
        "fog_color": np.array([0.5, 0.1, 0.55]),
        "on_transition_events": [['fog_beings', 60, 0]],
        "possible_transitions": ["forest_late_night", "mushroom", "foggy"],
        "season_preference": 0.88,
        "spookyness": 0.7,
        "starryness": 0.3,
        "transition_duration": 25,
        "transition_weights": [1, 0.4, 0.4],
        "tree_prob": 0.1,
        "wind_speed": 0.05,
    },

    WeatherState.SPOOKY: {
        "ARI": 15,
        "Switch_rate": 1.5,
        "Wolfy": 1,
        "ambient_sound": "294 Spooky Ghostly Moans (5) EDITED.wav",
        "celestial_visibility": 1,
        "firefly_density": 0.25,
        "fog": 0.65,
        "fog_color": np.array([0.7, 0.1, 0.1]),
        "possible_transitions": ["clear", "foggy", "firefly", "heavy_fog", "windy_night"],
        "sand_density": 0.1,
        "season_preference": 0.625,
        "spookyness": 1,
        "starryness": 1,
        "transition_weights": [1, 0.1, 0.3, 0.3, 0.2],
        "wind_speed": 0.2,
    },

    WeatherState.TEST_HUE_BIN: {
        "ARI": 9999,
        "Switch_rate": 1,
        "ambient_sound": "",
        "possible_transitions": ["test_rgb"],
        "transition_weights": [1],
    },

    WeatherState.TEST_RGB: {
        "ARI": 9999,
        "Switch_rate": 1,
        "ambient_sound": "",
        "possible_transitions": ["test_hue_bin"],
        "transition_weights": [1],
    },

    WeatherState.THUNDERSTORM: {
        "ARI": 39,
        "Sound_volume": 2,
        "ambient_sound": "Rain Heavy 01 EDITED.wav",
        "celestial_visibility": 0.1,
        "fog": 0.3,
        "fog_color": np.array([0.6, 0.6, 0.2]),
        "lightning_probability": 1,
        "possible_transitions": ["heavy_rain", "light_rain", "windy_night", "hurricane"],
        "rain_rate": 1,
        "season_preference": 0.9,
        "spookyness": 0.1,
        "starryness": 0,
        "transition_weights": [2, 0.3, 0.3, 0.6],
        "wind_speed": 1,
    },

    WeatherState.WINDY_NIGHT: {
        "ARI": 20,
        "Aurora_probability": 0.5,
        "Weird": 0.1,
        "Wolfy": 0.5,
        "ambient_sound": "Wind Strong EDITED.wav",
        "lightning_probability": 0.05,
        "meteor_rate": 0.1,
        "possible_transitions": ["clear", "heavy_rain", "sandstorm", "thunderstorm", "leaves", "hurricane", "desert_starlit_night", "desert_meteor_shower", "desert_blood_moon", "desert_dry_thunderstorm", "desert_dust_devil", "desert_oasis_night", "desert_twilight_blue", "desert_pre_dawn"],
        "rain_rate": 0.01,
        "sand_density": 0.2,
        "season_preference": 0.8,
        "spookyness": 0.01,
        "starryness": 1,
        "transition_weights": [1, 1, 0.6, 0.4, 0.5, 0.2, 0.9, 0.3, 0.3, 0.5, 0.5, 0.6, 0.7, 0.4],
        "tree_prob": 0.2,
        "wind_speed": 1.5,
    },

}

# Weather Sets - Mutually exclusive collections of weather states
WEATHER_SETS = {
    "bartiki": {
        "allowed_parameters": ["train_speed", "train_density", "fog", "fog_color", "Switch_rate", "ARI", "possible_transitions", "transition_weights", "season_preference", "starryness", "celestial_visibility", "rain_rate", "meteor_rate", "wind_speed", "firefly_density", "ambient_sound", "lightning_probability", "pride_intensity"],
        "background_events": ["bart_map", "stars", "clouds", "fog", "rain", "city_lights", "bay_shimmer", "pride_flag"],
        "cycle_labels": ["Midnight", "Sunrise", "Noon", "Sunset"],
        "description": "Bay Area BART system with day/night cycle — map by day, constellations by night",
        "name": "BarTiki",
        "narrative_script": "sounds/bartiki/script.json",
        "random_event_rate": 5e-05,
        "random_events": ["sunrise"],
        "season_extremity": 0.8,
        "season_speed": 1,
        "sound_pool_dir": "sounds/bart_sounds",
        "states": ["bartiki_dawn", "bartiki_morning_rush", "bartiki_midday", "bartiki_afternoon", "bartiki_evening_rush", "bartiki_dusk", "bartiki_night", "bartiki_late_night", "bartiki_stormy", "bartiki_pride"],
        "transition_speed": 1,
    },

    "beloved": {
        "allowed_parameters": ["wind_speed", "fog", "fog_color", "starryness", "celestial_visibility", "Switch_rate", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "season_preference"],
        "background_events": ["distant_lights", "warm_bloom", "heart_pulse", "thread_bonds"],
        "description": "Weather of the heart — passion, tenderness, longing, devotion. Driven by narrative variables.",
        "name": "Beloved",
        "narrative_script": "sounds/beloved/script.json",
        "random_event_rate": 6e-05,
        "random_events": ["heart_pulse", "warm_bloom"],
        "season_extremity": 0.6,
        "season_speed": 0.5,
        "sound_pool_dir": "sounds/beloved_pool",
        "states": ["love_infatuation", "love_tenderness", "love_longing", "love_devotion", "love_heartbreak", "love_reunion", "love_solitude"],
        "transition_speed": 0.5,
    },

    "cosmic_night": {
        "allowed_parameters": ["wind_speed", "starryness", "celestial_visibility", "meteor_rate", "Aurora_probability", "Switch_rate", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "season_preference"],
        "background_events": ["stars", "clouds"],
        "description": "Clear skies with meteors and celestial events",
        "name": "Cosmic Night",
        "narrative_script": None,
        "random_event_rate": 1.1e-05,
        "random_events": ["audio_balls", "sunrise", "fractal_fog"],
        "season_extremity": 1,
        "season_speed": 2,
        "sound_pool_dir": None,
        "states": ["clear", "windy_night", "asteroid"],
        "transition_speed": 2,
    },

    "cyberpunk": {
        "allowed_parameters": [
            "rain_rate", "wind_speed", "fog", "fog_color",
            "lightning_probability", "neon_intensity", "pollution_level",
            "hologram_density", "electric_interference", "data_flow_rate",
            "light_pollution", "drone_activity", "glitch_probability",
            "scan_line_intensity",
            # New cyberpunk shader params
            "cyber_rain_color",
            "cyber_signage_density", "cyber_skyline_density",
            "cyber_transit_intensity", "cyber_underway_intensity",
            "velocity_direction",
            "celestial_visibility", "starryness", "Switch_rate",
            "ambient_sound", "ARI", "possible_transitions",
            "transition_weights", "season_preference",
        ],
        "background_events": [
            # Generic shared shaders
            "clouds",                # backdrop layer above the city
            # State-tied cyberpunk backdrops (run continuously; controlled
            # by per-state density params)
            "cyber_smog_volume",
            "cyber_underway_glow",
            "cyber_transit_flow",
            "cyber_neon_grid",
            "cyber_city_skyline",
            "cyber_drone_spotlight",
            "cyber_neon_signs",
            "cyber_hologram_billboards",
            "cyber_data_rain",
            "cyber_rain",             # reads rain_rate + cyber_rain_color
            "cyber_electric_storm",   # reads lightning_probability + electric_interference
            "cyber_ar_glitch",        # reads glitch_probability (threshold 0.40)
            "cyber_scan_lines",
            # Narrative-variable layer (threshold-gated at story_* >= 0.2)
            "signal_carrier",
            "dread_perimeter",
            "yearning_gravity",
            "defiance_inversion",
            "dissolution_drift",
            "velocity_streaks",
        ],
        "description": "Neon-lit dystopian cityscape — Bay Stack megacity. Six narrative-variable shaders respond to active arc; 10 state-tied backdrops define the place.",
        "name": "Cyberpunk Metropolis",
        "narrative_script": "sounds/cyberpunk/sounds.json",
        "random_event_rate": 8e-05,
        "random_events": ["game_of_life", "tunnel", "pixel_spots"],
        "season_extremity": 0.5,
        "season_speed": 0.3,
        "sound_pool_dir": None,
        "states": [
            "cyber_neon_clear", "cyber_neon_drizzle", "cyber_data_storm",
            "cyber_smog_haze", "cyber_electric_storm", "cyber_acid_rain",
            "cyber_hologram_night", "cyber_blackout", "cyber_glitch_fog",
            "cyber_drone_patrol",
            # New states
            "cyber_dawn_pirate", "cyber_crown_vault", "cyber_midden_market",
            "cyber_underside_flood", "cyber_hour_of_static", "cyber_ar_bloom",
            "cyber_transit_corridor", "cyber_relay_node", "cyber_broadcast_night",
        ],
        "transition_speed": 0.8,
    },

    "desert_realm": {
        "allowed_parameters": ["wind_speed", "sand_density", "volcano_level", "fog", "fog_color", "starryness", "celestial_visibility", "firefly_density", "lightning_probability", "rain_rate", "spookyness", "Wolfy", "meteor_rate", "Sound_volume", "Switch_rate", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "transition_duration", "season_preference"],
        "background_events": ["background_director", "desert_sky", "desert_mountains", "desert_clouds", "desert_dunes", "desert_creatures", "sandstorm", "stars", "fog", "firefly", "desert_rain"],
        "cycle_labels": ["Midnight", "Dawn", "Noon", "Dusk"],
        "description": "Harsh desert with sandstorms and a full day/night cycle of dust, heat, and starlight",
        "name": "Desert Realm",
        "narrative_script": None,
        "random_event_rate": 7e-05,
        "random_events": [],
        "season_extremity": 1.5,
        "season_speed": 0.5,
        "sound_pool_dir": None,
        "states": ["sandstorm", "desert_blazing_noon", "desert_dusk_embers", "desert_starlit_night", "desert_oasis_night", "desert_dry_thunderstorm", "desert_dust_devil", "desert_harmattan", "desert_meteor_shower", "desert_blood_moon", "desert_pre_dawn", "desert_dawn", "desert_golden_morning", "desert_twilight_blue", "desert_day_rain", "desert_night_rain"],
        "transition_speed": 0.6,
    },

    "ethereal_mist": {
        "allowed_parameters": ["wind_speed", "rain_rate", "fog", "fog_color", "spookyness", "starryness", "celestial_visibility", "firefly_density", "Wolfy", "Switch_rate", "tree_prob", "Weird", "Sound_volume", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "season_preference"],
        "background_events": ["fog", "fog_beings", "firefly", "clouds"],
        "description": "Mysterious foggy realm with supernatural elements",
        "name": "Ethereal Mist",
        "narrative_script": None,
        "random_event_rate": 8e-05,
        "random_events": ["tentacle", "fractal_fog", "voronoi_sphere", "fog_beings"],
        "season_extremity": 1.5,
        "season_speed": 0.7,
        "sound_pool_dir": None,
        "states": ["heavy_fog", "foggy", "spooky", "mushroom", "firefly"],
        "transition_speed": 0.5,
    },

    "full_spectrum": {
        "allowed_parameters": ["wind_speed", "rain_rate", "lightning_probability", "starryness", "spookyness", "fog", "fog_color", "celestial_visibility", "firefly_density", "Aurora_probability", "Wolfy", "Switch_rate", "meteor_rate", "volcano_level", "sand_density", "skiptime", "tree_prob", "Weird", "Sound_volume", "season_preference", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "transition_duration"],
        "background_events": ["clouds", "firefly", "stars", "rain", "fog"],
        "description": "All weather states available - maximum variety",
        "name": "Full Spectrum",
        "narrative_script": None,
        "random_event_rate": 0.0001,
        "random_events": [],
        "season_extremity": 1,
        "season_speed": 1,
        "sound_pool_dir": None,
        "states": ["clear", "light_rain", "heavy_rain", "thunderstorm", "windy_night", "foggy", "heavy_fog", "spooky", "firefly", "sandstorm", "mushroom", "leaves", "bloom"],
        "transition_speed": 1,
    },

    "ocean": {
        "allowed_parameters": ["wind_speed", "fog", "fog_color", "wave_speed", "wave_amplitude", "bioluminescence", "tide_level", "bubble_density", "marine_life_activity", "kelp_density", "vent_activity", "Switch_rate", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "season_preference"],
        "background_events": ["Bioluminescence", "ocean_waves", "kelp", "bubbles", "fish", "fog", "smoker", "tube_worms"],
        "cycle_labels": ["Midnight", "Sunrise", "Noon", "Sunset"],
        "description": "Oceanic environment with waves and aquatic life - fog represents water clarity, season represents time of day",
        "name": "Ocean Realm",
        "narrative_script": None,
        "random_event_rate": 8e-05,
        "random_events": [],
        "season_extremity": 1.25,
        "season_speed": 2,
        "sound_pool_dir": None,
        "states": ["ocean_calm_shallows", "ocean_choppy_surface", "ocean_storm_surge", "ocean_deep_calm", "ocean_bioluminescent_swarm", "ocean_abyss", "ocean_kelp_forest", "ocean_coral_reef", "ocean_jellyfish_bloom", "ocean_midnight_open_water", "ocean_maelstrom", "ocean_tide_pool", "ocean_hydrothermal_vent"],
        "transition_speed": 0.7,
    },

    "peaceful_forest": {
        "allowed_parameters": ["wind_speed", "rain_rate", "fog", "fog_color", "starryness", "celestial_visibility", "firefly_density", "Aurora_probability", "meteor_rate", "tree_prob", "Weird", "Wolfy", "Owly", "Sound_volume", "skiptime", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "transition_duration", "season_preference", "Switch_rate", "spookyness", "lightning_probability", "godray_strength", "canopy_density", "snow_rate", "spore_density", "spore_color", "dapple_strength", "stream_flow_rate", "eye_density", "frost_level"],
        "background_events": ["clouds", "firefly", "stars", "rain", "fog", "forest_canopy", "canopy_godrays", "dappled_shadows", "snowfall", "spore_drift", "stream_flow", "forest_eyes", "forest_birds"],
        "cycle_labels": ["Midnight", "Dawn", "Noon", "Dusk"],
        "description": "Forest with full day/night cycle, seasonal moods, and aurora/storm/spirit variants",
        "name": "Peaceful Forest",
        "narrative_script": None,
        "random_event_rate": 2e-05,
        "random_events": ["sunrise"],
        "season_extremity": 1,
        "season_speed": 1,
        "sound_pool_dir": None,
        "states": ["forest_dawn", "forest_morning", "forest_midday", "forest_dusk", "forest_night", "forest_late_night", "forest_night_storm", "snowfall", "first_frost", "autumn_blaze", "aurora_grove", "spirit_grove", "forest_storm", "pollen_drift", "mushroom", "bloom", "leaves", "forest_golden_hour", "forest_bioluminescent", "forest_misty_dawn", "forest_pre_storm", "forest_breezy", "forest_migration", "forest_firefly", "forest_drizzle", "forest_thundershower", "forest_post_rain", "forest_night_drizzle", "forest_night_squall"],
        "transition_speed": 1,
    },

    "storm_world": {
        "allowed_parameters": ["wind_speed", "rain_rate", "lightning_probability", "fog", "fog_color", "starryness", "spookyness", "celestial_visibility", "Wolfy", "Switch_rate", "tree_prob", "Sound_volume", "skiptime", "ambient_sound", "ARI", "possible_transitions", "transition_weights", "season_preference"],
        "background_events": ["clouds", "rain", "fog", "stars", "firefly"],
        "description": "Intense weather with storms and high winds",
        "name": "Storm World",
        "narrative_script": None,
        "random_event_rate": 0.0001,
        "random_events": [],
        "season_extremity": 0.5,
        "season_speed": 1.5,
        "sound_pool_dir": None,
        "states": ["windy_night", "heavy_rain", "thunderstorm", "hurricane", "foggy", "light_rain", "sandstorm", "leaves", "firefly"],
        "transition_speed": 1.5,
    },

    "test": {
        "allowed_parameters": [],
        "background_events": ["test_pattern"],
        "description": "test system",
        "name": "test",
        "narrative_script": None,
        "season_extremity": 1,
        "season_speed": 1,
        "sound_pool_dir": None,
        "states": ["test_rgb", "test_hue_bin"],
        "transition_speed": 1,
    },

}

DEFAULT_WEATHER_SET = "bartiki"



def _validate_parameter_definitions():
    """Sanity-check that every parameter referenced by a weather set or
    preset has a PARAMETER_DEFINITIONS entry.

    Missing entries cause the web weather editor to silently skip the
    parameter (see the `if (!paramDef) continue;` in weather_editor.html),
    so even though the parameter still affects rendering, the user can't
    see or change its value. Surfacing the problem at import time turns a
    "why can't I edit this" mystery into an obvious warning.
    """
    import sys

    known = set(PARAMETER_DEFINITIONS.keys())

    missing_in_sets = {}
    for set_name, set_data in WEATHER_SETS.items():
        for param in set_data.get("allowed_parameters", []):
            if param not in known:
                missing_in_sets.setdefault(param, []).append(set_name)

    missing_in_presets = {}
    for state, preset in WEATHER_PRESETS.items():
        for param in preset.keys():
            if param not in known:
                missing_in_presets.setdefault(param, []).append(state.value)

    if not missing_in_sets and not missing_in_presets:
        return

    bar = "=" * 72
    lines = [
        "",
        bar,
        "[weather_params] parameters missing from PARAMETER_DEFINITIONS",
        "These will be silently skipped by the web weather editor.",
        "Add an entry in PARAMETER_DEFINITIONS for each one.",
        bar,
    ]
    for param in sorted(missing_in_sets):
        sets = ", ".join(sorted(missing_in_sets[param]))
        lines.append(f"  [set]    {param}  (in allowed_parameters of: {sets})")
    for param in sorted(missing_in_presets):
        states = ", ".join(sorted(missing_in_presets[param]))
        lines.append(f"  [preset] {param}  (in states: {states})")
    lines.append(bar)
    print("\n".join(lines), file=sys.stderr)


_validate_parameter_definitions()
